- csharp/src/cli/Commands/Cognito.cs
- csharp/src/cli/Commands/PublishCommand.cs
This PR adds password validation so that passwords are made to comply with the policy. It also fixes a problem with `PublishCommand.CanExecute` which caused the system to show the unrecognized function error if the user could not log in.
> CLI fixes related to #35.

- csharp/src/elements/Geometry/Polygon.cs
- csharp/src/elements/elements.csproj
- csharp/test/PolygonTests.cs
1) Fixed false positives on "Touches" when Polygons actually intersect.
2) Added methods for relationships between Vector3 point(s) and Polygons.
3) Multiple Polygon and Vector3 relationship methods are freestanding from single entity methods.
4) Simplified "Intersects" method.
5) Added Distinct operator to returned Clipper list on "Union" operation to avoid sending duplicate points to "ToPolygon".
6) Updated test suite to cover new methods.
> Polygon Fixes and Enhancements

- csharp/src/elements/Geometry/Polygon.cs
- csharp/src/elements/elements.csproj
1) Area compare method of Intersection was sometimes faulty due to integer / double conversion. This improved method is exact, deletes a few lines of code, and eliminates the "magic number" areaTolerance.
2) Bumped version number.
> Fixed bug in "Covers" which would give false negatives.

- src/Elements/Element.cs
- src/Elements/Model.cs
- src/Elements/Serialization/ElementConverter.cs
- src/Elements/Serialization/ModelConverter.cs
- test/ExtensionTests.cs
- test/elements-tests.csproj
This PR introduces the concept of an extension as specified in #107. Extensions allow the deserialization of arbitrary types that implement IElement, as long as those types are loaded into the app domain. Unlike the previous way of finding IElement types, where the deserializer attempted to reflect on all loaded assemblies, hitting errors as mentioned in #104.
The way this works is that an extension is registered whenever a developer puts an IElement into a Model. The extensions property is then serialized to the JSON. Upon deserialization, the converter attempts to find all the assemblies loaded in the current app domain that are listed in the extensions property, then to deserialize the IElement using a type contained in one of those assemblies.
> Extensions

- README.md
The docs are a bit out of date it seems, `WideFlangeProfile` has no constructor with 0 arguments.
Since this snippet of code is most likely to be copy-pasted by people starting with `Elements` (like i did 😎), this should be up-to-date.
> Update README.md starter code sample

- src/Elements/Geometry/Polyline.cs
- test/PolygonTests.cs
The Normalize method call when calculating the current vector is causing errors.  Line 166 does not want a normalized vector, it wants to compute how much of the full vector is needed to reach the desired paramter.  
Suggest adding a test in Polyline tests that looks like
``` C#
var r = Polygon.Rectangle(2,2);
Assert.Equal(new Vector3(1,1,0), r.PointAt(0.5));
```
This test, which uses a rectangle not of unit length will reveal the problem.
> Remove the .Normalize() to fix PointAtInternal

- src/Elements/Geometry/Vector3.cs
To solve #147 , I propose a different implementation for `GetHashCode()` on `Vector3`
> Change GetHashCode() on Vector3

- src/Elements/Serialization/glTF/GltfExtensions.cs
Users (aka Eric) might want to add geometry of an element as well as the geometry of the aggregated elements, so we should not return from the GetRenderDataForElement method just because we've finished adding the aggregated geometries.
> Don't return after adding IAggregateElement geometry

- src/Elements/Geometry/Polygon.cs
- test/PolygonTests.cs
I'm an idiot. For some reason I was moving all coordinates into the first quadrant. Got rid of Math.Abs of x and y coordinates at conclusion of Polygon Centroid calculation.
> Fixed Polygon Centroid coordinates for all quadrants.

- src/Elements/Geometry/Solids/Face.cs
- src/Elements/Geometry/Solids/Solid.cs
- src/Elements/Serialization/glTF/GltfExtensions.cs
- test/GridTests.cs
- test/IFCTests.cs
- test/StructuralFramingTests.cs
This PR addresses #177. Instead of writing tessellated solid data to a mesh and then converting that mesh into buffers appropriate for glTF, we write the tessellated solid information directly to buffers.
> Performance improvements for glTF write.

- src/Elements/Serialization/glTF/GltfExtensions.cs
This matches the behavior when there are no elements.
Manual testing: tested functions with and without geometry.
Fixes hypar-io/Explore#288
> Produce valid empty GLTFs when no elements produce geometry.

- src/Elements/Geometry/Transform.cs
- test/Elements.Tests/TransformTests.cs
Adding a few utility overloads to Transform.Scale(): 
```csharp
Transform.Scale(double amount)
Transform.Scale(double amount, Vector3 origin)
```
open to better/more efficient ways to scale about an origin without the double-translate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/225)
> add additional Scale overloads

- src/Elements/Geometry/Polygon.cs
- test/Elements.Tests/PolygonTests.cs
BACKGROUND:
there are methods in GeometryEx that are updated and need to live in Elements for other downstream functionality.
DESCRIPTION:
Move IsClockwise into Polygon class and use it to improve the Covers method.  
TESTING:
run the test called "Covers" in the file "PolygonTests.cs"  this test now includes a test of covers for a reversed polygon.
FUTURE WORK:
None
COMMENTS:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/237)
> take IsClockwise and covers from GeometryEx

- Schemas/Geometry/Profile.json
- src/Elements/Generate/Geometry/Profile.g.cs
- src/Elements/Geometry/Profile.cs
- test/Elements.Tests/ModelTests.cs
BACKGROUND:
- After the release of 0.5.1 it was found that older models which generated JSON in which profile voids were null, were not able to be merged by the export server, or consumed in downstream functions where the non-null requirement was imposed.
DESCRIPTION:
- This PR removes the restriction that `Voids` be defined and non-null.
TESTING:
- Update any function to use 0.5.2 (this version).
- Run that function in a workflow containing functions referencing an older version of Elements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/243)
> Allow null voids on Profiles.

- src/Revit/RevitHyparTools/Create.cs
- src/Revit/RevitHyparTools/WallByProfile.cs
BACKGROUND:
Floors need to use the revit floor thickness and they need to have a floor transform that describes their "top" rather than simply an elevate profile.
DESCRIPTION:
changes to how floors are drawn.
TESTING:
look at floors exported from Revit
FUTURE WORK:
None
COMMENTS:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/247)
> use thickness and appropriate z transform with floor profiles

- src/Dynamo/README.md
- src/Dynamo/src/HyparDynamo/Hypar.cs
- src/Dynamo/src/HyparDynamo/HyparDynamo.csproj
- src/Dynamo/test/FloorFromFloor.dyn
- src/Dynamo/test/WallFromWall.dyn
- src/Revit/RevitHyparTools/Create.Wall.cs
- src/Revit/RevitHyparTools/Create.cs
- src/Revit/RevitHyparTools/RevitExtensions.cs
- src/Revit/RevitHyparTools/RevitHyparTools.csproj
- src/Revit/RevitHyparTools/WallByProfile.cs
BACKGROUND:
We want to export walls from Revit as well as floors.
DESCRIPTION:
This PR adds nodes to extract walls, there is a new UserElement class created to make the wall from a face extracted from the Revit wall.
TESTING:
run `dotnet build` and checkout the new nodes.
FUTURE WORK:
This only handles Planar walls with a line centerline.
COMMENTS:
There are some geometry issues around the intersections of walls, the joining behavior is not kept with this method of gathering the wall geometry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/246)
> Add method for extracting walls from Revit models

- src/Elements/Geometry/Matrix.cs
- test/Elements.Tests/MatrixTests.cs
- test/Elements.Tests/TransformTests.cs
BACKGROUND:
transforms were not inverting when they should be able to
DESCRIPTION:
It fixes the determinant calculation (which had a typo) so that the `Inverse()` method doesn't throw erroneous errors
TESTING:
There is a new test called Involutory_Transform_Inverse
FUTURE WORK:
maybe a dedicated Determinant test
> fix determinant calculation

- src/Elements/Serialization/IFC/IFCElementExtensions.cs
- src/Elements/Serialization/IFC/IFCModelExtensions.cs
This PR add to the previous fix for #253 by removing all uses of the material's name as a dictionary key.
> Further fix of #253.

- src/Dynamo/src/HyparDynamo/HyparDynamo.csproj
- src/Revit/RevitHyparTools/RevitExtensions.cs
BACKGROUND:
publishing a dynamo package
DESCRIPTION:
- switch a method to internal that was private.  
- switch the target of our package target so that the package is built on `build` not only on publish.
TESTING:
- this is the setup that was used to deploy the currently published dynamo package
> deploy on build and make method internal

- src/Elements/Geometry/Vector3.cs
- test/Elements.Tests/VectorTests.cs
BACKGROUND:
- Julio Sarachaga from Lagersoft pointed out that Vector3.IsParallelTo was failing on two vectors one could reasonably expect to be parallel
DESCRIPTION:
- Adds a tolerance to the check, and unitizes vectors to ensure length is not a factor
TESTING:
- added a new test to verify this behavior (was breaking before in two ways, new test covers both)
> support tolerance for Vector3.IsParallelTo

- src/Elements/Analysis/AnalysisMesh.cs
- src/Elements/Geometry/BBox3.cs
- src/Elements/Geometry/Mesh.cs
- test/Elements.Tests/AnalysisMeshTests.cs
BACKGROUND:
- When testing against the work @andrewheumann is doing in #273, it was found that the analysis grid was really slow. We tracked this down to the analysis grid using `Grid2d` to support clipped analysis grids. This was allocating way too much stuff just to support grids that weren't square. 
DESCRIPTION:
- This PR makes analysis grids square. The grid is fit to the bounds of the perimeter polygon supplied. Analysis results within the perimeter are given a value and the vertices of the mesh are colored, otherwise the vertices are set to white.
- This PR changes `BBox3` to a struct and updates the tuple which stores results in `AnalysisGrid` to use a "cell" that is a `BBox3`. This reduces allocation.
- This PR tweaks the `AddVertex(...)` method making the `uv` parameter …
> Remove dependency on Grid2d from AnalysisGrid.

- src/Elements/Geometry/Containment.cs
- src/Elements/Geometry/Line.cs
- src/Elements/Geometry/Polygon.cs
- src/Elements/Geometry/Profile.cs
- src/Elements/Geometry/Ray.cs
- test/Elements.Tests/LineTests.cs
- test/Elements.Tests/RayTests.cs
- test/Elements.Tests/VectorTests.cs
BACKGROUND:
- Fixes #257 
- Attempts and fails to improve raycasting performance by implementing a Winding Number based polygon contains method. 
DESCRIPTION:
- Adds a `Ray.Intersects(GeometricElement)` method that accounts for the element's transform
- Adds a `Profile.Contains` method that can do region inclusion taking into account holes/voids
- Changes `Ray` to a Struct
- Updates `Ray.Intersects(Face)` to use the new hole-aware containment method
- Adds `Ray.Intersects(Line)`
TESTING:
- Run the updated `RayTests.RayShadowTest`
- Run the `VectorTests.ProfileContains` test (tests 100 points against a complex profile and ensures their inclusion results match those in Rhino / GH).
FUTURE WORK:
- The performance of the `Ray.Intersects()` operations could likely still be improved. 
- The …
> winding-based polygon contains, support for holes + xforms for ray intersection

- src/Elements/Units.cs
BACKGROUND:
In 0.7.0 of the `Hypar.Functions` we added the ability to add unit types to function inputs and outputs. The unit types enumeration should live in `Elements.Units`.
DESCRIPTION:
This PR adds the `UnitType` enumeration used by `Hypar.Functions`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/281)
> Add unit types.

- src/Elements/Geometry/Line.cs
BACKGROUND:
Lagarsoft ran into an exception when submitted a line to DivideByLength:
https://discordapp.com/channels/688033618303516701/688086821904580726/700051407235055686
DESCRIPTION:
Catches a situation where two points for a line fall within identical location tolerance.
TESTING:
Supply a line and diving length to leave a zero segment.
FUTURE WORK:
No.
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/290)
> Added check for zero length line for short segments

- CHANGELOG.md
- src/Elements/Geometry/Transform.cs
- src/Elements/Model.cs
- test/Elements.Tests/ColumnTest.cs
BACKGROUND:
See #170.
DESCRIPTION:
#170 was filed before we had done a big round of cleanup on our built in element constructors. The error there could not be reproduced. In writing a test to validate that this was no longer a problem, I added to convenience methods that make it easier to transform elements.
In the image below, the column on the left is created with a default transform and the column on the right is created with a transform including translation and rotation supplied in its constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/293)
> Add test for #170 and convenience transform methods.

- src/Elements/Geometry/Profile.cs
- test/Elements.Tests/ProfileTests.cs
BACKGROUND:
- Lagarsoft and past Eric both had reason to union profiles
DESCRIPTION:
- Add a union profile method
- Add two tests, that ensure voids are created correctly when profiles are unioned.
TESTING:
- can run profile tests and view resulting glb for visual inspection
FUTURE WORK:
- There are other boolean operations that it might be nice to support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/292)
> add profile union method and tests

- CHANGELOG.md
- src/Elements/Geometry/Arc.cs
- src/Elements/Geometry/Circle.cs
- src/Elements/Geometry/Curve.cs
- src/Elements/Geometry/Polygons.cs
- src/Elements/Geometry/Profile.cs
- src/Elements/Geometry/Profiles/HSSPipeProfile.cs
- src/Elements/Serialization/IFC/IFCExtensions.cs
- test/Elements.Tests/ArcTests.cs
BACKGROUND:
See #190.
DESCRIPTION:
This PR deprecates the `Polygon.Circle` method and adds `Circle.ToPolygon(...)` as well as a number of other useful implicit conversions between arcs and polylines and circles and polygons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/288)
> Deprecate Polygon.Circle.

- CHANGELOG.md
The fixes were listed with the shorthand #xxx, which is typically turned into a link in issues and PRs, but is not for other markdown documents. Here we replace those shorthand with proper links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/304)
> Change fixes to links.

- src/Elements/Geometry/Line.cs
- src/Elements/Geometry/Plane.cs
- src/Elements/Geometry/Vector3.cs
- test/Elements.Tests/LineTests.cs
BACKGROUND:
- #307 
DESCRIPTION:
- In order to fix #307, a number of changes needed to be made:
- Extend `Line.Intersects(Plane p)` to support infinite lines
- Add a `Line.Intersects(Line l)` to support 3d line intersections
- Edit `Line.TrimTo(line l)` to use the new Line.Intersects() method
- Edit `Line.ExtendTo(line l)` to use the new Line.Intersects() method
- Add `Plane.ClosestPoint(Vector3 p)`
- Add `Plane.SignedDistanceTo(Vector3 p)`
TESTING:
- Run `LineTests.Extend` and `LineTests.LineTrimToInYZ`
FUTURE WORK:
- There are probably more concise ways to do 3d line/line intersection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/308)
> fix TrimTo in 3d

- src/Elements/Generate/TypeGenerator.cs
- src/Elements/Serialization/IFC/IFCElementExtensions.cs
- src/Elements/Serialization/JSON/JsonInheritanceConverter.cs
- test/Elements.Tests/ModelTests.cs
- test/Elements.Tests/TypeGeneratorTests.cs
- After MUCH trial and error, I believe these to be the minimum changes necessary to bring the main Elements library up to speed with the modifications I made for the Grasshopper plug-in and Runner. 
- I have been running around since march trying various multi-targeting solutions — it appears these were not necessary, and the following changes are sufficient to get the library working with grasshopper.
- Makes the Type Cache on the `JsonInheritanceConverter` static, and exposes a public method to refresh it. In the grasshopper context, new types may have been dynamically loaded since the `JsonInheritanceConverter` was initialized, so it needs to be refreshed before deserializing a model.
- Initializes the `id` variable before use. This was throwing errors back when I was trying to …
> Elements compatibility with Grasshopper library

- src/Elements/Spatial/Grid1d.cs
- src/Elements/Spatial/Grid2d.cs
BACKGROUND:
- In order to support Grid functionality in grasshopper, it needs to be easy to make a deep copy of Grid types (so that changes to an object in a downstream component don't change the object upstream)
DESCRIPTION:
- Adds a Grid1d(Grid1d other) constructor
- Adds a Grid2d(Grid2d other) constructor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/318)
> Add a duplicate constructor for Grid1d and Grid2d

- src/Elements/Geometry/Mesh.cs
BACKGROUND:
- couldn't figure out why my normals from GH meshes weren't showing
- turns out they were just being ignored
DESCRIPTION:
- uses the supplied normal in the Vertex constructor if present
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/327)
> Vertex Constructor should respect supplied normal

- src/Elements/Geometry/Mesh.cs
BACKGROUND:
- It is possible to construct a mesh including a vertex with no triangles. In this case, the ComputeNormals() method will throw an exception due to dividing by zero. 
DESCRIPTION:
- Adds a check for a vertex triangle count = 0, returning a 0 normal in that case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/328)
> fix for computeNormals exception

- src/Elements/Geometry/Arc.cs
- src/Elements/Geometry/Bezier.cs
- src/Elements/Geometry/Curve.cs
- src/Elements/Geometry/Interfaces/ICurve.cs
- src/Elements/Geometry/Interfaces/ITransformable.cs
- src/Elements/Geometry/Line.cs
- src/Elements/Geometry/Polygon.cs
- src/Elements/Geometry/Polyline.cs
- src/Elements/Geometry/Ray.cs
- src/Elements/Geometry/Transform.cs
BACKGROUND:
- Needed to be able to transform any curve, and wanted to avoid a switch statement cycling through the `Transform.OfXXXX` methods.
DESCRIPTION:
- Adds an `ICurve Transformed(Transform)` to `ICurve`
- Implements it as `public abstract` in `Curve`
- Moves the `Transform.OfXXXX`  code from `Transform` to each curve type's `Transformed()`  method, and leaves the old `OfXXXX` methods in place but just call the Transformed methods inside
- Adds additional transform methods for `Arc` and `Polyline`
- Marks the old `OfXXXX` methods as Obsolete
TESTING:
- Tested in GH context, passes all tests
FUTURE WORK:
- It's a little annoying that you have to cast the result back to the curve type. I couldn't figure any good way to do this. I think in RhinoCommon their `Duplicate` method has a …
> Transformed() methods for curve types

- src/Elements/Geometry/Line.cs
- test/Elements.Tests/LineTests.cs
- test/Elements.Tests/ProfileTests.cs
BACKGROUND:
- Needed a trim method for lines
DESCRIPTION:
- Adds a `Line.Trim(Polygon)` method
- Fixes a bug with `Line.Intersects(Line)` where it would report a false positive for intersection. 
- Adds a `Line.PointOnLine(Vector3 point)` method
TESTING:
- Have added `LineTrimWithPolygon()` to LineTests, and verified that it does the right thing for lines starting inside a polygon, lines starting outside a polygon, lines fully inside or outside a polygon, lines that end along an edge of the polygon, and lines that cross the polygon at a vertex (both passing through at the vertex and grazing the vertex). 
FUTURE WORK:
- It would be nice to also have a Line.Trim(Profile) or Line.Trim(List<Polygon>) method that build on this one.
--- …
> trim line with polygon

- src/Elements/Geometry/Line.cs
- src/Elements/Geometry/Vector3.cs
BACKGROUND:
- Building functionality for a client function, and encountered several limitations / bugs with Elements
DESCRIPTION:
- adds a flag on `Line.Intersects(Line)` to indicate whether intersections exactly at the ends should be considered. In some cases, this may be undesirable (e.g. find self-intersections in a polygon), while in others it is useful (e.g. split a line with other lines). 
- also adds this flag to `PointOnLine`, for the same reason.
- fix behavior of "infinite" mode on `Line.Intersects(Line)`
- fixes a bug where the `AreCollinear` method would return false for a set of collinear vertices if it contained duplicates
- `Vector3.ClosestPointOn(Line)` would return points that were not on the line, this is fixed. For infinite use cases we should add a similar method when …
> Line and vector

- src/Elements/Generate/TypeGenerator.cs
BACKGROUND:
- code generation started to fail after a change to make it run async.  the failure was misplaced commas that were not consistent or correct in constructor args.  @ikeough  correctly identified that the template variable controlling comma placement were being shared across code generation threads.
DESCRIPTION:
- Turn on a flag for template thread safety in dotliquid.  this fix is documented here: https://github.com/dotliquid/dotliquid/pull/220 
TESTING:
- I ran hypar cli locally and this seems to get past the identified issue.  
FUTURE WORK:
- CLI needs to reference this change for it to be fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/334)
> set global flag to make templates threadsafe

- src/Elements/Model.cs
BACKGROUND:
- Elements types that have `Dictionary<string,double>` (or similar) properties in their schemas will throw exceptions on Hypar during serialization.
- This is because the dictionary "Check" was casting the incoming dictionary to `IDictionary<string, object>`, which will return null for an IDictionary of another type. 
- Then this property would fall through to recurse further, and fail on line 252 `var pValue = p.GetValue(obj, null);`
DESCRIPTION:
- Replace the cast check with one to IDictionary instead of IDictionary<string, object>
- iterate over dict.Values
TESTING:
- tested with [a schema that was failing](https://raw.githubusercontent.com/hypar-io/unispace/optimizationFunction/cellGeneration/OptimizedSpaceAssignment/OptimizationResults.json?token=AHTU2EYYDVXFFC4FW6VIS6K66D …
> Check for IDictionary instead of IDictionary<string,object>

- src/Elements/Generate/TypeGenerator.cs
BACKGROUND:
- async code generation requires a couple more changes
DESCRIPTION:
- move the thread safe setting up in the execution tree, we only need to set it once.  
- create and use the HyparFilters which is only necessary while the LiquidFilters class is marked internal see this Issue: https://github.com/RicoSuter/NJsonSchema/issues/1199 
TESTING:
- code gen for JSONtoModel seems to work great now, with the correct naming as well.
FUTURE WORK:
- We'll want to remove the duplicate code when that issue gets resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/337)
> global template settings incl filters

- src/Revit/Hypar.Revit.sln
- src/Revit/HyparRevit/Hypar.Revit.csproj
- src/Revit/HyparRevit/HyparContextServer.cs
- src/Revit/HyparRevit/HyparHubApp.cs
BACKGROUND:
In its initial release Hypar for Revit deserialized elements from models in the hub, then generated graphics from the geometry in those elements. This required building an assembly of the dependent types and loading it and created the restriction that we couldn't reload that assembly when a workflow was changed by adding or removing a function that used new types.
DESCRIPTION:
This PR removes element deserialization and reads geometry buffers directly from gltfs and into Revit buffers. This has the following benefits:
- It is faster. No assembly creation, loading, or deserialization of JSON models is required.
- It enables update of visualization when functions are added or removed from a workflow without stopping the hub and restarting Revit. The hub functionality to enable …
> Send gltf buffers to Revit DirectContext3D directly.

- src/Elements/Generate/TypeGenerator.cs
related to https://github.com/hypar-io/Hypar/pull/230
Custom elements were no longer codegenning correctly for several reasons. Above PR corrects the first, this corrects the other.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/350)
> fix for element codegen

- src/Elements/Generate/TypeGenerator.cs
BACKGROUND:
- In order to support `input_schema` codegen for Locations, the schema for GeoJSON.Point needed to be added to known schemas. In order to support `input_schema` codegen for other built-in special types, the method for listing the excluded (known) types needed to be made public.
DESCRIPTION:
- Adds ` https://geojson.org/schema/Point.json` to `_hyparSchemas`
- exposes `GetCoreTypeNames()` as public
TESTING:
- Have tested with a new version of the CLI that relies on these changes (PR forthcoming)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/351)
> add point schema

- src/Elements/Generate/TypeGenerator.cs
- src/Elements/Templates/Class.Constructor.Record.liquid
BACKGROUND:
- CodeGen was failing on elements with property names that included "." characters, and likely many other cases. 
DESCRIPTION:
- copies ToSafeIdentifier back into Elements, with a TODO about consolidating once codegen can rely on Hypar.Model
- adds a PropertyNameGenerator that calls on ToSafeIdentifier
- adds a new Liquid filter, that also calls on ToSafeIdentifier
- adapts code templates to use the new filter
TESTING:
- codegen on a file referring to [this schema](  https://raw.githubusercontent.com/andrewheumann/AndrewSchemas/master/AreaTally.json) would fail, now it does not
FUTURE WORK:
- TypeGeneration should be moved out of elements, and the new copy of the string utils removed
--- …
> Sanitize argument + property names

- src/Elements/Geometry/Polygon.cs
- src/Elements/Geometry/Polyline.cs
- src/Elements/Geometry/Profile.cs
- src/Elements/Geometry/Vector3.cs
- src/Elements/Spatial/Grid2d.cs
- test/Elements.Tests/PolygonTests.cs
BACKGROUND:
- Anthony ran into some consistent issues with performing a boolean difference between two polygons that share an edge, as reported here: https://github.com/hypar-io/Elements/issues/358
- this PR fixes some but not all of the cases in his report. There may be fundamental limits to clipper's ability to handle this kind of condition. 
DESCRIPTION:
- replaces the global constant `CLIPPER_SCALE` with per-function tolerance values that default to the global tolerance `Vector3.EPSILON`
- changes the rounding behavior of ToClipperPath to round to the nearest integer instead of rounding down
TESTING:
- have added a test adapted from @anthonyhauck's (and a note about the cases where it continues to fail)
- have tested a number of operations at various tolerance levels
- have ensured no …
> Polygon Boolean Improvements

- Elements/src/Geometry/Vector3.cs
- Elements/test/VectorTests.cs
BACKGROUND:
- Wall export from revit was failing with line end points being the same.  This was traced back to a bad transform that was flattening the z coordinate of all points.  Bad transform made because a bad vector was accepted while trying to choose a transform from a list of points.  The dot product check for >< 1 did not include a tolerance check.
DESCRIPTION:
- add tolerance check to dot product comparison.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/366)
> use epsilon tolerance while creating transfor from points

- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- JSON to model was failing on recent exports from Revit.  We know now that it is because of the ModelPoint objects that had no points in them.
DESCRIPTION:
- The gltf export should not fail even if there's an empty ModelPoints object.  We check if there are any points before adding them to the gltf.
TESTING:
- I have used a local reference to Elements in the JSON to Model function and it works with this change, successfully not exporting points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/367)
> don't add empty model points

- Elements/src/GeometricElement.cs
- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
- Elements/test/ModelTests.cs
BACKGROUND:
For Python functions, we want to be able to generate geometry from a JSON. Currently, deserializing into types that inherit from `GeometricElement` requires having a concrete type available in the context into which you can deserialize. This is not necessary as all `GeometricElement` have a `Representation` property that contains the geometry required to visualize.
DESCRIPTION:
This PR adds another fall-through case on the JSON converter that attempts to build a `GeometricElement` if the type can't be deserialized using the typical routes. As an example, I exported the Simple Tower project to JSON and deserialized it using the updated converter, then saved to a .glb. The result can be seen below. This model contains a number of types (`Envelope`, `Level`, and `FacadePanel`) …
> Deserialize to GeometricElement even when a type isn't recognized.

- Directory.Build.props
After removing Elements as a submodule from Hypar, the build script no longer placed a `/nupkg` folder with the built packages at the root of the Elements directory. This was due to the lack of the `Directory.Build.Props` file which, in addition to specifying where to put the built packages also specified the version number for the build. This PR adds a `Directory.Build.props` file identical to the one in Hypar so that the build script works correctly when run from Hypar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/371)
> Fix build after separation from core.

- Elements.CodeGeneration/src/TypeGenerator.cs
- Elements.CodeGeneration/test/TypeGeneratorTests.cs
BACKGROUND:
- Coge gen failed when there were two schemas that each referenced another, because that last, referenced, schema would be duplicated when it existed in both classes
DESCRIPTION:
- Improve testing of multi-schema code gen
- Use the TypeArtifact from NJson generator to get the code for each type
- Use the templating tools directly to get the code for each file
TESTING:
- pull the branch and run the tests
- I have also used this local CLI to publish aliaxis functions that will break otherwise.
FUTURE WORK:
- Still have not completed the refactor of AssemblySave / AssemblyLoad that should merge their inner loops.  I'd like to do a file-reorg as well.
COMMENTS:
- Although I have tests for generating in-memory code and saving dlls, no guaruntee that when Excel and GH go to use this …
> Gen separate files

- Elements/src/Geometry/Kernel.cs
- Elements/src/Geometry/Profile.cs
- Elements/src/Validators/Validators.cs
- Elements/test/ProfileTests.cs
BACKGROUND:
- There was a bug that permitted profile voids to be oriented incorrectly relative to the outer perimeter, such that holes would not show up in an extrude. (Fixes https://github.com/hypar-io/Elements/issues/372) 
-  fixes https://github.com/hypar-io/Elements/issues/373
DESCRIPTION:
- Fixes void orientation relative to the perimeter with an OrientVoids() method that gets called in the constructor.
- Rename Profile.Reverse() => Profile.Reversed() for consistency
- Check profile normal before doing an extrude, and flip if they are anti-parallel to prevent inside-out extrusions
- adds a new test to verify that void orientation is corrected in the Profile constructor.
TESTING:
- Create a profile with voids oriented the same way as the perimeter — check that the voids get …
> fix void orientation for profiles and profile orientation for extrudes

- Elements.CodeGeneration/src/TypeGenerator.cs
BACKGROUND:
- In order to support data inputs on input_schema, we need to 
1. publish the InputData class as a schema https://github.com/hypar-io/Hypar/pull/253,
and 2. add it to the list of known types that codegen shouldn't generate (this PR)
TESTING:
Have built the CLI with this change, and tried building a function that refers to the InputData schema and tested that it successfully builds the inputs class with a proper reference to the built-in type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/375)
> add InputSchema to known types

- Elements.CodeGeneration/src/TypeGenerator.cs
BACKGROUND:
- Element Types that had any a nested portion of their schema lacking a "Title" property would fail codegen.  
DESCRIPTION:
- use the type hint name if the schema title is null or empty
TESTING:
- previously, this schema would fail codegen: 
```json
{
"$id": "https://hypar.io/Schemas/MeshList.json",
"$schema": "http://json-schema.org/draft-07/schema#",
"description": "Data from a file input.",
"x-namespace": "Hypar.Functions.Execution",
"title": "MeshList",
"type": "object",
"properties": {
"meshes": {
"type": "array",
"$ref": "https://hypar.io/Schemas/Mesh.json"
}
},
"additionalProperties": false
}
```
- now it works
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/el …
> handle missing type titles

- Elements/src/Geometry/Polygon.cs
BACKGROUND:
- Sometimes you just have a bunch of polygons and you want to union them together — there's no distinct "set A" and "set B"
DESCRIPTION:
- Creates an additional method that simply calls the existing union method with the second list empty
TESTING:
- Have tested the "second list empty" method in my own functions, it works as expected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/379)
> Add a static "Union" method accepting only one list of polygons

- Elements/src/Model.cs
BACKGROUND:
- Element types are not found unless this cache gets refreshed
DESCRIPTION:
- add a call to JsonInheritanceConverter refresh user element types cache right before de-serializing models from json.
TESTING:
- This works when referenced locally, and solves some issues.
FUTURE WORK:
- NA
COMMENTS:
- NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/386)
> refresh inheritance cache

- Elements.CodeGeneration/src/TypeGenerator.cs
BACKGROUND:
- While working on the export server we found out it was failing to generate the correct code, because it lacked the correct parm filters, and also possibly due to thread issues, although those weren't as obvious, they did result in strange behavior during debug.
DESCRIPTION:
- Add the line for supporting async to each code gen entry point.  
- Add the line for registering the name converting filters to each code gen entry point.
TESTING:
- Code gen when loading multiple templates into memory.  Test code for the ExportServer would help you test this change if you wanted to run it locally. https://github.com/hypar-io/api/tree/migrate-export-server/ExportServer
--- …
> add thread-safe and filters to all code gen paths

- Elements.CodeGeneration/src/Elements.CodeGeneration.targets
BACKGROUND:
- sam deployment failed due to `publish` not copying the Templates folder the way `build` does.
DESCRIPTION:
- Include the copy target both before build and before publish
TESTING:
- Locally if you run dotnet publish with a project that references this nuget package the Templates folder will appear in the publish directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/389)
> copy on publish

- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- gltf exporting caused failures in the export server.
DESCRIPTION:
- don't add material with missing texture paths.
- ignore meshes where the mesh is null.
TESTING:
- the temporary stack ew-sand has an export server that uses this version of Elements, you can use this workflow to see two functions that normally break being exported.
https://dev.hypar.io/workflows/4442ed8d-b409-409c-96e3-b756b0491258?api=ew-export
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/390)
> check missing texture and null mess

- Elements/src/Serialization/glTF/GltfExtensions.cs
The accessor count was inadvertently used where the node count should be, leading to glbs which had incorrect node array sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/413)
> Fix bug with solid glb creation.

- .github/workflows/build-and-publish-alpha.yml
There was one line missing from the action. This caused the action to fail validation when the first sync to master happened after the action was introduced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/429)
> Fix the action.

- Elements/src/Elements.csproj
BACKGROUND:
- the csg library wasn't found while working on the ExportServer lambda in the api repo
```
There was an error writing an element of type Elements.Beam to IFC: Could not load file or assembly 'Csg, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```
DESCRIPTION:
- Add the setting `CopyToOutputDirectory=Always`
TESTING:
- next nuget package will work.  it's also running live on the sam stack `api=ew-export` which you could use from explore while exporting gltf.
FUTURE WORK:
- need to confirm this setting is all we need for nuget packages to always have this file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements …
> always copy the csg lib

- .github/workflows/publish-on-tag.yml
Use the GITHUB_REF to get the tag version of the current release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/434)
> Use GITHUB_REF.

- Elements/src/Elements.csproj
BACKGROUND:
- still can't get csg in nuget package
DESCRIPTION:
- add the csg.dll explicitly as content like the texture.
TESTING:
- using a nupkg extension for vscode I can see that the nupkg has the csg.dll file now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/435)
> different packing strategy

- Elements/src/Elements.csproj
BACKGROUND:
- still can't get csg
DESCRIPTION:
- explicit package path
TESTING:
- don't bother, we have to get published to nuget to test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/437)
> now pack with path

- Elements/src/Geometry/Transform.cs
- Elements/test/TransformTests.cs
BACKGROUND:
CSGs were failing to boolean properly with strange results. We found that vertical sweeps had their geometry inverted. This was due to an inverted Y axis of the transforms along a line causing transforms to not be "right handed".
DESCRIPTION:
This PR properly orients transforms along vertical curves and adds a test to ensure vertical curves in the up and down direction both work correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/445)
> Fix issue with inverted vertical curve transforms.

- Elements/src/Geometry/Line.cs
- Elements/test/LineTests.cs
BACKGROUND:
- Failed to get all segments for a line when asking for divide by
DESCRIPTION:
- Add a tolerance to the check of whether to stop segmenting, approxEquals for endpoint checks in PointAt, and a test
TESTING:
- run the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/442)
> use approx for pointAt and epsilon for divide by

- Directory.Build.props
- Elements.CodeGeneration/src/Elements.CodeGeneration.csproj
- Elements.Serialization.IFC/src/Elements.Serialization.IFC.csproj
- Elements/src/Elements.csproj
- LICENSE.md
BACKGROUND:
While diagnosing an error with missing content in the CLI, we found that some content files were not being copied to the output directory when building projects with these packages as dependencies. It seems that a 
DESCRIPTION:
This PR adds the `PackageCopyToOutput` field in the csproj files, which encodes the content as requiring `copyToOutput=true`
With this change, the package manifest is as follows (note the addition of `copyToOutput: 'true'` in the `contentFiles` section):
```
Metadata:
id: Hypar.Elements
version: 1.0.0
title: Hypar Elements
authors: 'Hypar, Inc.'
requireLicenseAcceptance: 'false'
projectUrl: 'https://github.com/hypar-io/elements'
description: A building elements library for AEC.
copyright: 'Hypar, Inc. 2020'
tags: 'AEC, Architecture, Structure, …
```
> Use PackageCopyToOutput.

- .github/workflows/build-and-publish-alpha.yml
- .github/workflows/publish-on-tag.yml
This PR removes uses of the `set-env` command which are now illegal from actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/448)
> Remove disallowed set-env command.

- Elements/src/Geometry/Polygon.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- Polygon.UnionAll did not work as expected when supplied with a list of overlapping polygons. Because we were using Clipper's EvenOdd PolyFillType by default, it treated the overlapping region between two polygons as a "hole" when it should have been added to the union. 
DESCRIPTION:
- Adds a parameter to BooleanTwoSets to govern which PolyFillType to apply
- Sets UnionAll to use VoidTreatment.IgnoreInternalVoids
- Preserves existing behavior for other non-static cases, which will allow us to join two shapes-with-holes and get a correct result.
TESTING:
- Run the new `PolygonTests.UnionAll` test
FUTURE WORK:
- It's conceivable that we might need to expose this option all the way to the user.
--- …
> Fix Union All overlap treatment behavior

- Elements/src/GeoJSON/Geometry.cs
- Elements/src/Geometry/Circle.cs
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Polyline.cs
- Elements/src/Validators/Validators.cs
- Elements/test/SolidTests.cs
- Schemas/Geometry/Polyline.json
BACKGROUND:
See #461.
DESCRIPTION:
This removes the validation that polylines must be coplanar, adjusts docs accordingly, and updates methods to support 3d polylines where appropriate.
TESTING:
- I updated tests and verified that results looked reasonable. Coplanar polyline sweeps are unchanged and non-coplanar sweeps look reasonable:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/463)
> Fix #461: Support 3d polylines

- Elements/src/Geometry/Curve.cs
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Polyline.cs
- Elements/test/ModelCurveTests.cs
BACKGROUND:
- What led to this work, and what is the broader context of this change?
DESCRIPTION:
- Adds implicit conversion from Curve => ModelCurve to make quick visualization of a curve more terse in syntax
- Adds an extension method `Line.ToPolyline()`
- Adds a test ensuring that `Model.AddElement(Curve c)` converts as expected
TESTING:
- New test is added for the modelcurve conversion
FUTURE WORK:
- Similar conversions for `Representation` from `SolidOperation` — (deferring until Ian's work on Representations comes through)
- We may also want to make explicit extension methods to perform these conversions — they would not be more terse, but would be more discoverable. 
COMMENTS:
- the `Element(Polygon c)` conversion on the Polygon class may seem redundant, but it is necessary to …
> Utility Conversions for Curve => model curve and Line => Polyline

- Elements/src/Geometry/Vector3.cs
BACKGROUND:
- Got NaN results back from AngleTo because varialbe `r` was -1.0000002, and -1 is not a valid number to use in Acos function.
DESCRIPTION:
- round the value that is going into Acos to the 5th digit.
TESTING:
- Tests pass, works now in my function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/470)
> round value before ACOS

- CHANGELOG.md
- Elements.CodeGeneration/src/TypeGenerator.cs
BACKGROUND:
During testing of 0.8.1-alpha9 with the Hypar CLI, @wynged found that the `TypeGenerator.GetCoreTypeNames()` API was in fact required.
DESCRIPTION:
This PR introduces the `TypeGenerator.CoreTypeNames` property which wraps `_coreTypeNames`. A property is preferred over the method that we had previously because a method is no longer required to get the core type names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/477)
> Add a getter for CoreTypeNames.

- CHANGELOG.md
We have not been good about changelog updates. This includes all updates going back to the 0.8.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/478)
> Changelog updates for 0.8.1.

- Elements/src/Geometry/Vector3.cs
BACKGROUND:
- method was returning NaN
DESCRIPTION:
- We also check the -1 case, and return 180
TESTING:
FUTURE WORK:
CHANGELOG:
- [ x] `CHANGELOG.md` is updated as necessary.  not necessary for this fix I don't think.
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/481)
> also return 180 if (dot / length ~ -1), it's close

- CHANGELOG.md
- Elements/src/Model.cs
- Elements/test/UserElementTests.cs
BACKGROUND:
- deserialization of some user elements failed.  it turned out it was elements that relied on Profiles created inside the UpdateRepresentation method.  
DESCRIPTION:
- serialize the exportModel that is created.  This model is the one that ensures all necessary child elements are serialized before the parent, so deserialization can happen correctly.
- lint fix in Changelog, looks big, it just removes a bunch of whitespace.
TESTING:
- The test has been modified and will succeed with this change.  Simplest addition to the test is that we assert there are no errors during deserialization.
FUTURE WORK:
- I think we might be about to remove UpdateRepresentation, so this might be unnecessary soon.
CHANGELOG:
- [x ] `CHANGELOG.md` is updated as necessary. 
COMMENTS: …
> Fix model serialization

- CHANGELOG.md
- Elements/src/Model.cs
- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
- Elements/test/ModelTests.cs
- Elements/test/UserElementTests.cs
BACKGROUND:
- Model de-serialization was broken in the Revit context due to assembly loading issues.
DESCRIPTION:
- catch type load errors, and simply skip them while building the type cache.
- Allow these errors to be added to the `Model.FromJson` error list
- Refactor to iterate over types only once while building cache.
- fixed #484 
TESTING:
- Use in Revit Context, and/or observe that all tests continue to work.
FUTURE WORK:
CHANGELOG:
- [ x] `CHANGELOG.md` is updated as necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/485)
> catch type load errors while building type cache. 

- CHANGELOG.md
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- I was developing this method for a specific function and realized it probably belongs in Elements proper.
DESCRIPTION:
- Adds the ability to translate just one 'segment' of a polygon (two consecutive vertices). 
- Throws an exception if the requested transformation is not within the polygon's current plane.
- Triangles skip this check, since they are always planar.
TESTING:
Tests in the code:
- One-axis transformations of a square on the XY plane
- Two-axis transformations of a square in 3D space
- Confirm no work is done if specified segment does not exist
- Confirm function throws in request motion in non-planar
FUTURE WORK:
- There may be valid transformation cases that we support but I didn't realize! These should probably have tests.
- Some shapes may have valid …
> Add Polygon.TransformSegment()

- CHANGELOG.md
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolygonTests.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
- I need the ability to find shared segments between polygons for another function. I thought it would be useful to include in elements.
DESCRIPTION:
- Adds a static `Polygon.SharedSegments()` method.
- Given two polygons, it returns a set of tuples for any shared segments
- A 'shared segment' means the start and end points are the same (although possibly reversed)
- The tuple is of the segment indices for their respective polygons. They can be different, hence tuple instead of just `int`.
TESTING:
Tests in code are:
- Concentric polygon circles return no results
- Intersecting polygon circles return no results
- Identical polygon circles return ten accurate results
- Identical polygon circles (one reversed) return ten accurate results
- A pair of squares with one shared edge …
> Add Polygon.SharedSegments()

- CHANGELOG.md
- Elements/src/Serialization/JSON/MeshConverter.cs
BACKGROUND:
- There is an alternative schema format that is used in the front end that we would like to be able to deserialize when it is in the present on an input_schema.
DESCRIPTION:
- Identify the other schema type by the presence of the "vertices" property.
- If this is the "input mesh" then deserialize into the mesh type in a slightly different way.
TESTING:
- The Roof By Sketch function is proof of this functionality working, it has temporarily been published with a local elements reference.
FUTURE WORK:
- We should make an effort on both the Hypar web app and in this library to converge on a single mesh schema representation, as outlines in the note above the converter code.
CHANGELOG:
- [x ] `CHANGELOG.md` is updated as necessary. 
COMMENTS:
---
This change …
> allow alternative mesh deserialization

- CHANGELOG.md
- Elements/src/Spatial/Grid1d.cs
- Elements/src/Spatial/Grid2d.cs
- Elements/test/Grid2dTests.cs
BACKGROUND:
- trying to update a grid2d's component 1d grid axis after creation would fail to update its 2d cells, if the `Cells` property on the 2d grid had already been accessed
DESCRIPTION:
- Allows invalidation of the parent 2d grid's cells if the child U or V grid is modified
- Prevents invalidation of the parent grid and throws an exception if a user attempts to modify the axis grid when there has already been 2d subdivision (as this would destroy the already-modified inner 2d cell) 
TESTING:
- New tests have been added 
- This change is being used already in functions for a customer
REQUIRED:
(no public method / docs changes)
--- …
> Grid2d updated from axis change fix

- .github/workflows/build-and-publish-alpha.yml
BACKGROUND:
- I just merged #505 but accidentally left unnecessary (and long-running steps) in the `build-and-publish-alpha` workflow
DESCRIPTION:
- Removes unnecessary steps (install mono + docfx) from the alpha release job
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/506)
> Remove unnecessary cicd steps

- .github/workflows/build-and-publish-alpha.yml
BACKGROUND:
- I left out two critical steps from #506
DESCRIPTION:
- Removes copy of build docs step in main alpha release workflow (since it lives in its own step now)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/508)
> remove docs build from not-docs-build step

- CHANGELOG.md
- Elements/src/Geometry/Transform.cs
BACKGROUND:
- A user assumed that the Transform constructor would unitize direction axes, when this was not the case. This is a pretty reasonable assumption to make, so let's make it true (non-uniform transforms can still be created with Transform.Scale).
DESCRIPTION:
- unitizes axis vectors
TESTING:
- Tests continue to pass
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/511)
> unitize axes

- .github/pull_request_template.md
BACKGROUND:
- thanks to @cdriesler, docs now automatically get updated via CICD, so no longer need to be included in our PR template
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/515)
> remove docs step

- CHANGELOG.md
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/src/Serialization/glTF/GltfMergingUtils.cs
- Elements/test/ContentTests.cs
BACKGROUND:
- Adding content elements to the GLTF was slow, partly because we repeatedly fetch the glb from the url.
DESCRIPTION:
- Create a cache for memory streams that will be used anytime a url is recognized.
TESTING:
- there's a test that asserts the speed difference.
FUTURE WORK:
REQUIRED:
- [ x] All changes are up to date in `CHANGELOG.md`.
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/539)
> Cache glb streams

- .github/workflows/build-and-publish-alpha.yml
BACKGROUND:
- bad workflow
DESCRIPTION:
- move the `result-encoding` field
TESTING:
- we'll see!!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/542)
> put result encoding in with

- .github/workflows/build-and-publish-alpha.yml
BACKGROUND:
- we have a better strategy for getting the most recent tag, based on date.
- We have had recent failures to publish Elements alphas, but because tags are created after publish, this resulted in cascading failures as nuget version was ahead of the tag version in our repo.
DESCRIPTION:
- Use a custom git command to get the lastest tag based on creatordate
- move the creation of the alpha tag prior to nuget publishing, so we continue to increment repo tags even if nuget publish fails for some reason.
TESTING:
- new version command works in the `Hypar` repo.
FUTURE WORK:
- Monitoring.
REQUIRED:
COMMENTS:
--- …
> Improved get previous tag

- CHANGELOG.md
- Elements/src/Geometry/Polygon.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- I found some cases where polygons reported a false containment with a vertex that was above the polygon
DESCRIPTION:
- Adds an internal middleware function that checks for vertices on the XY plane, and runs the calculation on a transformed polygon and point if it is not an XY plane polygon
TESTING:
- See the new test for the previously failing case
FUTURE WORK:
- Make more cohesive our strategy for 2D and 3D geometries.
REQUIRED:
COMMENTS:
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/565)
> Polygon.Contains expanded 3D support

- Elements/src/Spatial/CellComplex/CellComplex.cs
- Elements/test/CellComplexTests.cs
BACKGROUND:
- #546 deployed, but an example was missing in the docs for `CellComplex`
DESCRIPTION:
- Tweaks test names and comments so that the example for `CellComplex` shows up in my local docs build
TESTING:
- Build docs
FUTURE WORK:
- N/A
REQUIRED:
COMMENTS:
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/568)
> Ensure CellComplex examples show up in docs

- Elements/src/Analysis/ColorScale.cs
BACKGROUND:
- Merged #532 and realized I forgot to address a final comment from the PR
DESCRIPTION:
- Makes non-public constructor internal
- Cleans up comments that were throwing linter errors
TESTING:
- Ran deserialization test again and ensured that it passed.
FUTURE WORK:
- N/A
REQUIRED:
COMMENTS:
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/569)
> Follow-on cleanup to color scale interpolation

- CHANGELOG.md
- Elements/src/Geometry/Solids/ConstructedSolid.cs
- Elements/src/Geometry/Solids/Solid.cs
- Elements/src/Serialization/JSON/SolidConverter.cs
- Elements/test/SolidTests.cs
BACKGROUND:
- #572 
- We need to be able to pass the Solid held by a Constructed Solid from function to function
DESCRIPTION:
- Ensures the `Solid` of a `ConstructedSolid` serializes.
TESTING:
- Added a test which serializes + deserializes a model containing ConstructedSolid
FUTURE WORK:
- `ConstructedSolids` don't convert to IFC correctly, this should be corrected.
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/574)
> Serialize the solid associated w/ a constructedSolid

- CHANGELOG.md
- Elements/src/Spatial/Grid2d.cs
- Elements/test/Grid2dTests.cs
BACKGROUND:
- We had a request from some customers to simplify excluding incomplete cells from a grid2d. Prior to this PR, you had to do this to get "untrimmed cells within the boundary":
```
Grid2d.GetCells().Where(c => c.IsTrimmed() && c.GetTrimmedCellGeometry.Count() > 0);
```
which is cumbersome.
DESCRIPTION:
- Adds a `treatFullyOutsideAsTrimmed` flag to `IsTrimmed()` (true by default) which counts cells entirely outside of the boundary as "trimmed." This is left as a flag, in case a user wants the old behavior (for instance, tallying facade panels that are odd shapes and need a different manufacturing process — in this case we would not want to consider non-existent panels.)
TESTING:
- Updated the test 
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> allow isTrimmed to return true for cells outside the boundary

- docs/Revit.html
BACKGROUND:
- We now use a separate repo for Revit addon releases and we have much more documentation around converters.
DESCRIPTION:
- Change a link to point to the newer installer locations
- Add more links to further documentation about authoring converters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/578)
> Doc path update

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Vector3.cs
- Elements/src/Spatial/Grid2d.cs
- Elements/test/Grid2dTests.cs
- Elements/test/LineTests.cs
BACKGROUND:
- A Grid2d created in a workflow had U and V curves that did not match the input directions.
DESCRIPTION:
- Adds optional `tolerance` parameter to `Line.ExtendTo(Polygon)`, `Line.ExtendTo(IEnumerable<Line>)`, `Vector3.IsParallelTo(Vector3)`.
- Uses these parameters to override tolerances for `Grid2d` constructor.
TESTING:
- Run the new test `SkewedGridsWithNearlyParallelBoundary`.
FUTURE WORK:
- We may want to add `tolerance` parameter to the rest of `Line.ExtendTo` signatures, if this approach works well.
- This may also be relevant in the `AreCollinear` method as well.
REQUIRED:
COMMENTS:
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/580)
> Fix: Grid2d from origin, U, and V directions may change the axes slightly.

- .github/workflows/publish-on-tag.yml
BACKGROUND:
- Hypar.Elements.Components is successfully released on alphas, but I forgot to add it to the action that releases for full versions, so our full versions were missing. 
DESCRIPTION:
- Adds Hypar.Elements.Components to our deploy on tag action.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/582)
> deploy Hypar.Elements.Components to nuget on full releases

- CHANGELOG.md
- Elements/src/Analysis/AnalysisMesh.cs
- Elements/test/AnalysisMeshTests.cs
BACKGROUND:
- I made an analysis mesh in a "all one color" situation, and it crashed
DESCRIPTION:
- Help the analysis mesh handle the case where there's just one value, and so min==max and then span / 0.
TESTING:
- I've used this in a function.
- The new test passes.
FUTURE WORK:
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/583)
> handle when the span is 0 for an analysis grid

- CHANGELOG.md
- Elements/src/Geometry/Polygon.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- Polygon.Split would fail or give incorrect results for polygons not in the world XY plane, or not counter-clockwise wound.
DESCRIPTION:
- Transforms a polygon into its XY plane before trying to split it, and then transforms its results back.
- Adds a `ToTransform()` method to `Polygon` which produces a consistent transform with its Z axis along the polygon's normal. Using `Vertices.ToTransform()` was not yielding consistent results.
TESTING:
- Added new tests, verified old split tests still pass.
FUTURE WORK:
- We might want to enable `Profile` methods to be more tolerant of non-XY orientations as well
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elemen …
> Support non-xy splits

- CHANGELOG.md
- Elements/src/Spatial/Grid1d.cs
- Elements/test/Grid1dTests.cs
BACKGROUND:
- Previously, Grid.SplitAtPoint() and other methods would wind up splitting at the wrong point, due to their reliance on a dumb algorithm, which ignored the length of segments and calculated a position that assumed a straight-line axis.
DESCRIPTION:
- Adds a more sophisticated ClosestPosition algorithm that actually calculates the closest point on a polyline axis and computes the cumulative length up to that point.
TESTING:
- Added a new test that failed in previous versions of Elements, and passes now. 
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/590)
> better handle closestPosition on polyline axes

- CHANGELOG.md
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Vector3.cs
- Elements/test/PolygonTests.cs
- Elements/test/VectorTests.cs
BACKGROUND:
- The CollinearPointsRemoved  is to be used in the function for lights placement.
DESCRIPTION:
- The AreCollinear for 3 points is used in CollinearPointsRemoved. CollinearPointsRemoved is good to have for the algorithms that work on Polygon and, for example, wants to know which segment is the longest.
TESTING:
- CollinearPointCanBeRemoved is added to PolygonTests and Collinear to VectorTests
FUTURE WORK:
REQUIRED:
- [x ] All changes are up to date in `CHANGELOG.md`.
COMMENTS:
There is AreCollinear extension of the list of Vector3d but it's not convenient for the case if you don't have a list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/600)
> Add Polygon.CollinearPointsRemoved and Vector3.AreCollinear(a,b,c)

- Elements/src/Geometry/Polygon.cs
BACKGROUND:
- Daniel Fink noted that the `Polygon.IsClockwise` method doesn't work for 3d polygons.
DESCRIPTION:
- This adds a note (yes, we should add a function), that clarifies that the method is only appropriate for 2D polygons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/599)
> Add more explanation for IsClockwise.

- CHANGELOG.md
- Elements.CodeGeneration/src/TypeGenerator.cs
BACKGROUND:
- https://github.com/hypar-io/Elements/issues/616
DESCRIPTION:
- Supplies a document path to the NJsonSchema code generator utilized by `generate-types`
TESTING:
- I utilized the test examples provided by @Gytaco and verified that the local reference to Vector2 was resolved and generated. `hypar generate-types -u `
FUTURE WORK:
- We'll need to release a CLI Alpha built against this version of elements for it to be useful 
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/617)
> supply local document path for codegen

- CHANGELOG.md
- Elements/src/GeometricElement.cs
- Elements/src/Geometry/CsgExtensions.cs
- Elements/src/Geometry/Representation.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- A customer is having trouble with complex geometries rendering strangely in the UI, due to CSG failures.
DESCRIPTION:
- Adds a `SkipCSGUnion` flag to `Representation`, which is hidden from docs + not included in `Representation`'s serialized form.
- If present on a representation, its solids are meshed without being unioned, and its void forms are discarded.
TESTING:
- I created a function that utilized this flag w/ a local version of elements to verify it handled a large collection of "pixelated" geometry. https://dev.hypar.io/workflows/233c4148-ee66-4a5d-ac43-486907b9ff6b
FUTURE WORK:
- We should move towards an easier way for users to produce lightweight, mesh-based representations for situations like these.
REQUIRED:
COMMENTS:
- This feels like a hack. We should move to …
> csg union flag

- Elements.Serialization.DXF/src/ContentElementToDxf.cs
BACKGROUND:
- DXF export would fail if any content elements didn't have the new Symbols property
DESCRIPTION:
- Allows export to ignore content elements w/o symbols
FUTURE WORK:
- render *something*, like a bounding box, if a content element has no symbol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/628)
> Handle no symbols on content element

- Elements/src/Spatial/HalfEdgeGraph2d.cs
- Elements/test/ProfileTests.cs
BACKGROUND:
- @ikeough identified a case in which the polygonizer would produce an incorrect polygon.
DESCRIPTION:
- Corrects a case in the section of the Polygonizer which is responsible for cleaning up "tails" of duplicate edges. 
This code was designed to cover this case: 
However, in the case that the pair of edges (0,9) being removed straddled the end of the edge list, the code would successfully remove those two edges (0, 9) and then decrement `i` in order to find the next potential pair of edges to remove. However, since it started with i=9, it would decrement to 8, and bypass the remainder of the "paired" edges. In this case we now decrement a second time, to make sure we're still addressing the correct pair of edges. 
TESTING:
- A new test is added, and all existing tests pass. …
> fix for dangle cleanup

- Elements/src/Geometry/Line.cs
BACKGROUND:
- The `Line.Thicken` method did not work for lines where the z-values of the start and end points are almost equal (for example, 0 and 1.7763568394002505E-15)
DESCRIPTION:
- What does this PR specifically accomplish?
TESTING:
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/635)
> Fix equality comparison of floating point numbers in Line.Thicken method

- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Profile.cs
- Elements/src/Geometry/Ray.cs
BACKGROUND:
A function is using Polygon.Contains in a tight loop across many vertices. The Segments() call in Contains represents a significant portion of total runtime (~40%). 
DESCRIPTION:
This updates Contains to use the new Edges() method from Ian's draft PR #638. This has roughly the same performance as moving the Segments() call outside the inner loop.
TESTING:
This method has existing unit test coverage, which still pass. I also linked these changes into the function we've been optimizing and found 30-50% improvement to relevant code.
FUTURE WORK:
- More code can be updated to use Edges, some of which is already updated in Ian's #638.
REQUIRED:
- [N/A] All changes are up to date in `CHANGELOG.md`.
--- …
> Accelerate Polygon.Contains(Vector3) by iterating directly over vertices

- CHANGELOG.md
- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
BACKGROUND:
- while working in Revit we ran into an issue where Newtonsoft 9.* is loaded, and it does not have a method we use during model serialization.
DESCRIPTION:
- Switch to using `TryGetValue` which should do basically the same thing, but appears to be available in older version, and thus works in Revit 2020.
TESTING:
- behavior is unchanged.
FUTURE WORK:
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/644)
> use tryGetValue becuase it exists in older version of Newtonsoft

- CHANGELOG.md
- Elements/src/Geometry/Transform.cs
- Elements/test/TransformTests.cs
BACKGROUND:
- For a great many of our fluent-ish APIs, we supply both `.verb()` (e.g. `Move()`) methods to modify a thing in place, and `.participle-adjective()` (e.g. `Moved()`) to return a new version of the thing with a change applied. Transform had `.Invert()` but not `.Inverse()`.
DESCRIPTION:
- Adds `Transform.Inverse()`
TESTING:
- Added a `Transform_Inverse` test to `TransformTests`.
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/646)
> Add Transform.Inverse()

- CHANGELOG.md
- Elements/src/Geometry/Matrix.cs
- Elements/src/Geometry/Transform.cs
- Elements/test/TransformTests.cs
BACKGROUND:
- Consensus was that "Inverted" was more consistent than "Inverse"
- We also wanted to rename Matrix.Inverse to Matrix.Inverted (by obsoleting .Inverse)
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/648)
> inverse => inverted

- Elements/src/Geometry/Vector3.cs
- Elements/test/VectorTests.cs
BACKGROUND:
- `Vector3Extensions.AreCollinear` didn't work for coincident points. 
- A vector with almost zero values will still be unitized
DESCRIPTION:
- Add tolerance to Vector3.Unitized
TESTING:
- Added a new test, which used to fail, and now succeeds
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/650)
> Add tolerance to Vector3.Unitized

- .github/workflows/build-and-publish-alpha.yml
I've found a more reliable way of retrieving the latest version tag as long as we keep doing semver.  Had to exclude 'v' prefix since we don't use that lately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/653)
> version retrieval accoring to semver (ignoreing v*)

- CHANGELOG.md
- Elements/src/Geometry/CsgExtensions.cs
- Elements/src/Geometry/GraphicsBuffers.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/test/CsgTests.cs
BACKGROUND:
- Some shapes were showing up inexplicably dark in the viewport, despite having been consistently constructed. 
- This was because certain meshes had incorrect vertex normals, as verified in a GLTF debugger:
- This was due to an invalid assumption in the code: that a normal calculated from the first three vertices of a polygon would necessarily be the correct normal for that face. In fact, if the polygon face was non-convex, and the first three vertices fell within a concave portion, then the "triangle" we were using to calculate the normal would be wound clockwise relative to the polygon it came from. 
DESCRIPTION:
- Switches to using a tessellated triangle as the basis for the normal, which is guaranteed to lie within the CSG face polygon and be correctly wound.
TESTING:
- I …
> Fix GLB Vertex normals

- CHANGELOG.md
- Elements/src/Geometry/ConvexHull.cs
- Elements/src/Geometry/Vector3.cs
- Elements/test/ConvexHullTests.cs
BACKGROUND:
- I have a collection of points in 3D and I want their bounding frame in 3D along a given perspective line.
DESCRIPTION:
- Add the Frame3DPoints to ConvexHull static classes.
- tweak `Average` Vector3 extension to operation on IEnumerable.
TESTING:
- run the test to view the resulting glb.  (viewing in our viewer lets you use ortho mode which can be nice)
FUTURE WORK:
- There is probably a more performant way to do this, but we can optimize later if necessary.
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/660)
> Add a convex hull frame in 3d method and tests

- Elements.Benchmarks/Elements.Benchmarks.csproj
- Elements.Benchmarks/Program.cs
- Elements/src/Geometry/CsgExtensions.cs
- Elements/src/Geometry/GraphicsBuffers.cs
- Elements/src/Geometry/Solids/Solid.cs
- Elements/src/Geometry/UV.cs
- Elements/src/Geometry/Vector3.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/test/CsgTests.cs
During discussions of compiling Elements to wasm, we began to investigate sources of slowness in the gltf conversion path. There were a number of opportunities for small improvements, like reducing allocation of new polygons, and removing unnecessary creation of `Vector3` when converting from another vector type. 
- Removes the use of octree for merge vertex lookup during CSG output to graphic buffers.
- Removes use of `polygon.Transformed()` and `polygon.Reversed()` in `Solid`. Those methods both allocate new polygons which is not required as the transforms and winding can be handled while building face loops.
- Adds a couple of method to `Vector3` to allow dot and cross products to be calculated using components of an incoming vector.
Writing all HSS members to gltf before:
| …
> GlTF export performance improvements

- CHANGELOG.md
- Elements/src/Geometry/Polygon.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- We want to trim a door cutout from a wall perimeter leaving the "whole" wall perimeter behind.
DESCRIPTION:
- Add a method that will allow you to trim vertices from a polygon given an input curve, accepts lines, polylines and polygons.
TESTING:
- The tests work for trimming corners from a square and also trimming a door-like notch from a polygon.
FUTURE WORK:
- We may want to support other curve types in the future, it's easiest if they implement `DistanceTo()`
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/663)
> Remove vertices near curve

- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
- In Aliaxis workflow bug was discovered then routing algorithm could not correctly go down in the grid if points, algorithm should travel though is inside obstacle. It should have go though closest line but  instead it had broken  path, partially through obstacle. 
DESCRIPTION:
- This fixes bug when grid sometimes doesn't remove vertices inside obstacles
TESTING:
- Added AdaptiveGridSubtractBoxSmallDifference test to cover this exact case
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/672)
> AdaptiveGrid.SubtractBox cover the corner case when result is between two tolerances

- Elements.Components/src/SpaceConfiguration.cs
BACKGROUND:
- @serenayl noticed that instances of content elements in hyparspace were named with their URLs
DESCRIPTION:
- Uses the content item's name, instead of its url, if present as the basis for the rule name, which ultimately becomes the instance name.
TESTING:
- I published a version of lounge layout on dev built against this version of elements.components, and verified that the name was correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/674)
> use content name instead of URL as rule name

- CHANGELOG.md
- Elements.Serialization.IFC/src/Serialization/IFC/IFCExtensions.cs
- Elements.Serialization.IFC/test/IFCTests.cs
- Elements/src/Floor.cs
- Elements/src/GeometricElement.cs
- Elements/src/Geometry/Solids/SolidExtensions.cs
- Elements/src/Opening.cs
- Elements/src/StandardWall.cs
- Elements/src/Wall.cs
- Elements/src/WallByProfile.cs
- Elements/test/FloorTests.cs
- Elements/test/VectorTests.cs
- Elements/test/WallTests.cs
BACKGROUND:
- We want to change walls to support a variety of diverse wall types and to improve the openings API.
DESCRIPTION:
- update floor tests to confirm opening behavior is unchanged.
- deprecate wall Height and Profile of Wall.
- add Perimeter to WallByProfile and update constructors.
- add a direction to opening to support openings that are vertical
- add a test for `NormalFromPlanarWoundPoints` wich wasn't the problem (opening normals was) but I figure doesn't hurt.
TESTING:
- WallByProfileFromProfile test produces a wall with an opening.
FUTURE WORK:
- More WallByProfile changes and opening tweaks are likely as I work with exporting from Revit.
REQUIRED:
COMMENTS:
--- …
> Wall from profile

- CHANGELOG.md
- Elements/src/BuiltInMaterials.cs
- Elements/src/Material.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- gltf materials are keyed by name. This can cause errors like https://github.com/hypar-io/Elements/issues/460, and complicates mapping from materials in a model to the materials in the gltf.
DESCRIPTION:
- Changes our GLTF generation to utilize material ids instead of material names
TESTING:
- I built a function with this branch, and verified that materials still rendered correctly and had appropriate ids. 
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/683)
> use material id for name instead of name

- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- When skip CSG unions is _true_ we still should be able to modify vertex attributes
DESCRIPTION:
- Added passing `geometricElement.ModifyVertexAttributes` to the Tesselate method when CSG unions are skipped
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/689)
> Use colorization when SkipCSGUnion is true

- Elements/src/Ceiling.cs
BACKGROUND:
- We add elevation to the Transform inside constructor. If this constructor is used as as JSONConstructor, elevation will be added twice to transform (1 - during creation, 2 - during deserialization) 
DESCRIPTION:
In this PR an private constructor is added that do not add elevation to the Transform
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/700)
> Added private constructor to ceilings that marked as JSONConstructor

- CHANGELOG.md
- Elements/src/Geometry/Polygon.cs
- Elements/src/Spatial/Grid2d.cs
- Elements/test/Grid2dTests.cs
BACKGROUND:
- When working on Grid2d based on boundary that is not rectangular - getting trimmed geometry is failed completely sometimes.  Intersection returns quantized distances with step of tolerance.
If intersection region is one EPSILON wide it's highly unstable:
4.00001 - 4 = 9.9999999996214228E-06 but 4 - 3.99999 = 1.0000000000065512E-05.
And so, such region may be cut off by Intersection - in this case the cell is just skipped.
But if number passed the tolerance test - chances are high it will fail after fromGrid transformation is applied and then whole trimming process will fail.
Also, since polygon doesn't check number of vertices where was other unstable behaviour:
-Polygon has RemoveSequentialDuplicates in constructor that removes points less than tolerance away.
- Then, if …
> Grid2d change tolerance used for GetTrimmedGeometry.

- Elements.CodeGeneration/src/Elements.CodeGeneration.csproj
- Elements/src/Elements.csproj
- Elements/src/Geometry/Profiles/ParametricProfile.cs
BACKGROUND:
We've recently noticed that the size of Elements build directory has started to increase, affecting the size of functions on Hypar. One major cause of this bloat is the inclusion of extra language resources related to the use of the `Microsoft.CodeAnalysis.Scripting` package used by the parametric profile.
DESCRIPTION:
This PR reduces the Elements published size from 22.3mb to 16.4mb by disabling the inclusion of satellite resources. Sorry Italy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/702)
> Don't bundle other language resources.

- Elements/src/Geometry/Solids/Solid.cs
BACKGROUND:
- Solid.SweepFace does not create normals during tesselation.
DESCRIPTION:
- Add normals to the Mesh.
TESTING:
- Check the graphics buffer output for the normals.
FUTURE WORK:
- No.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/709)
> added normal into Sold Sweep Face mesh creation

- Elements/src/Geometry/Line.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
- Currently as 2 lines get close to parallel if using the first 3 points of a line the plane normal will be zero and you will get an error return.
DESCRIPTION:
- This performs a  simple check to see if the plane normal is zero and if so check the next 3 points between the two lines to get a plane.
TESTING:
- Run the test before using the fix then run the test after
FUTURE WORK:
- Potentially there could be other conditions where the plane normal is zero but hopefully this solves 99% of the use cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/712)
> Intersect fix for Plane Normal Zero error

- CHANGELOG.md
- Elements/src/Geometry/BBox3.cs
- Elements/src/Geometry/Mesh.cs
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Polyline.cs
- Elements/src/Geometry/Solids/Solid.cs
- Elements/src/Spatial/HalfEdgeGraph2d.cs
- Elements/src/Topography.cs
- Elements/test/HalfEdgeGraph2dTests.cs
- Elements/test/TopographyTests.cs
BACKGROUND:
- Users have requested the ability to create new Topography elements from a mesh.
DESCRIPTION:
- Adds an overload for the Topography constructor which can consume a custom mesh.
This required a number of additional changes:
-  added `HalfEdgeGraph.Construct(IEnumerable<Line> lines)`
-  added `Polyline.Project(Plane plane)`
-  added a new mesh constructor that duplicates an existing mesh `new Mesh(Mesh mesh)`
- refactored `Polygonize` to support different (non-polygon) output
TESTING:
- I added a `CreateTopoFromMesh` test which creates a topography from mesh.
- I added several `HalfEdgeGraphFromLines` tests which test creating polygons from line networks
- I created a function which makes a mesh via Delaunay triangulation, and verified that I could create a topography from it, …
> support for topography from mesh

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- a Hypar Space workflow demonstrated an issue where no walls were being generated between offices.  This turned out to trace backwards through `Grid.GetCellSeparators()` => `Line.Trim(Polygon)`.
- Specifically, a line that started just outside of a polygon — almost exactly within tolerance of the edge — was showing as "greater than tolerance" in one check (The perpendicular distance check in Polygon.Contains, Polygon.cs, line 495) but "less than tolerance" in the other (The "duplicate point" check in Line.Trim, Line.cs line 877).
- Since the point was seen as outside, but then the second point was ignored as a duplicate, `Line.Trim` was assuming the whole segment lay outside of the trimming polygon. If the first check had been under tolerance, it would have returned a …
> Fix Line Trim when a vertex is very close

- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
- All our polyline offset methods produce closed polygons. We need one that can produce an open polyline from an open polyline.
DESCRIPTION:
- adds a new `Polyline.OffsetOpen` method
TESTING:
- A new `OffsetOpen` test is added:
FUTURE WORK:
- This is a very naïve method. It does not handle eliminating self-intersections at concave corners, as seen in the test image. It also assumes 2D only. `OffsetOnSide` has better corner handling (but does not join the individual polygonal segments), and it would be nice to shift the logic of this method to take on similar behavior for the sake of consistency.
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/717)
> Open Polyline Offset

- .github/workflows/build-docs.yml
BACKGROUND:
- the `Build Docs` action had to be manually triggered via `workflow_dispatch`, so it hadn't been updated in 8 months
DESCRIPTION:
- Switches `Build Docs` to run on major version release.
TESTING:
- I tested the previous build docs action to make sure it still worked, but the trigger won't be tested until we do another release. If it fails then, it's not catastrophic, but we'll follow up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/724)
> Build Docs on Release

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
- After updating Elements to the latest version code that used Adaptive grid didn't traverse it as expected anymore.
- The reason was changing tolerance of intersect from Epsilon to Epsilon * 2. New tolerance is still better because grid doesn't fail randomly anymore but only individual cells with width [0, Epsilon] may appear. 
- Was also discovered that `AddEdge` that should have created new vertices after a lot of intersection operations didn't do so because it has wrong calculations inside of its fast checks that were designed to improve operation performance. Everything worked fine before because split points were aligned between regions of the grid.  Since adding regions to the grid was biggest bottleneck for large grid create from many regions, I decided not to fix …
> AdaptiveGrid: Remove AddEdge that does intersections. Double the Tolerance.

- Elements.Components/src/ContentCatalogRetrieval.cs
- Elements.Components/src/SpaceConfiguration.cs
BACKGROUND:
- There were some challenges in utilizing content configurations dynamically within a function.
- The ContentConfiguration class dynamically matches content in referenced configurations to a loaded catalog assumed to be at `./catalog.json`  via the `ContentCatalogRetrival` class.
DESCRIPTION:
- Adds `[JsonIgnore]` attribute to the computed ContentElement property, which is only needed at runtime
- Support specifying a different `catalog.json` path in case the catalog was fetched dynamically in a function and needs to be saved to a `temp` location.
TESTING:
- I created a `Create Content Configuration` function (see dev workflow `acdeaa39-f97a-46fd-856d-50fc76910bb9`) that loads a content catalog on the fly and then instantiates it using the components framework.
---
This change …
> Permit using Content Configurations dynamically

- Elements/src/Geometry/Profile.cs
See Hypar postmortem here: https://www.notion.so/hyparaec/2021-12-10-SkyCiv-fails-because-Structure-function-has-beams-with-unnamed-profiles-4d4fa6973ca441e6b77bc28284b96573
This PR sets the name on a new `Profile` created using `Profile.Transformed()` to the value of the `Name` on the original `Profile`. It does not carry over the `Id`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/728)
> Set name on new profile created during Transform.

- CHANGELOG.md
- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- https://github.com/hypar-io/Elements/issues/719
- Repeatedly running a test, or using `hypar run` with a function utilizing content elements can be painfully slow, since the referenced GLBs were getting fetched every single time. 
DESCRIPTION:
- Adds a completely optional disk cache for `GltfExtensions.gltfCache`, which is only utilized if `gltfExtensions.GltfCachePath` is set. 
TESTING:
- Running off local elements, I tested the following:
- running a generated function test with content elements that I modified by setting `GltfCachePath` at the beginning of the test. I verified that each subsequent test ran MUCH faster than the first one, and that files were getting stored at the specified directory.
- Using the `hypar run` command, with its server project modified to set …
> set up an optional disk cache for content element glbs

- CHANGELOG.md
- Elements/src/Search/Network.cs
- Elements/test/NetworkTests.cs
BACKGROUND:
- @mattc's work on path finding identified that debugging networks was difficult.
DESCRIPTION:
- This PR adds the `Network.ToModelText` method to visualize network node indices and their connected indices, and replaces several places in the code where we were doing this, with calls to the new method.
TESTING:
- The network tests have been updated to include this functionality. Run the network tests and visualize the results in your glTF viewer of choice.
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/725)
> Add ToModelText method.

- CHANGELOG.md
- Elements/src/GridLine.cs
- Elements/test/GridLineTests.cs
BACKGROUND:
- The gridlines as currently specified in the schema manager support arbitrary geometry. We would like to retain this flexibility.
DESCRIPTION:
- Deprecates `GridLine.Line` and uses `GridLine.Curve` instead.
- Adds `GridLine.GetCircleTransform()` method to help with text placement, which is still currently separate from GridLine geometry.
TESTING:
- Try the updated test examples for multiple gridlines with `ModelText`, as well as for a curved GridLine.
FUTURE WORK:
- How can we also include the text piece of this?
REQUIRED:
COMMENTS:
- Rolls in and should supersede #713
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/727)
> Support curved gridlines

- Elements/src/Search/Network.cs
BACKGROUND:
Network Traverse function can loop in some cases. For example, if leaf is very close to the edge, so for all calculations it's on the edge, but Network is still "think" that it's a leaf (it's smth we need to fix). So, when we are trying to travers network CCW, we got loop:
Because Leaf is almost on nearest edge, algorithm cannot use it and finds other edge that can be CCW. As result in a few step we get loop.
DESCRIPTION:
This PR contains condition inside Traverse  method: exit if we have already passed two elements in the same order
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/738)
> Updated condition of the Traverse function exit;

- Elements.Benchmarks/ElementCreation.cs
- Elements.Benchmarks/Trace.cs
BACKGROUND:
In prepation for #742, we need to have trace tests that enable us to generate speedscope files for JSON and glTF serialization.
DESCRIPTION:
- This PR separates the trace tests into two:
- `TraceJsonSerialization`
- `TraceGltfSerialization`
- This PR makes slight modifications to the `DrawAllBeams` benchmark method to minimize model recursion and to set the `SkipCsgUnion` flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/743)
> Setup for tessellation tracing.

- Elements/src/Elements.csproj
- Elements/src/extension.dib
BACKGROUND:
- Dotnet Interactive Notebooks support [extensions configured as scripts](https://github.com/dotnet/interactive/blob/788323abc710272a6fbd6bd9f51e3958e408b71a/docs/extending-dotnet-interactive.md#script-based-extensions). This permits adding special notebook-only functionality, without adding any dependencies on notebook-specific packages to the core library.
DESCRIPTION:
- Adds a helper script that runs when `Hypar.Elements` is imported into a dotnet interactive notebook. This helper creates a formatter for the `Model` type which renders a small threejs window to display a model, so that in code you can just `return model;` and see the model in 3d. It also adds a global `DisplayModel` method which can take a variable width and height.
TESTING:
- I temporarily renamed the …
> Add notebook helpers for elements

- CHANGELOG.md
- Elements/src/DirectionalLight.cs
- Elements/src/Geometry/Color.cs
- Elements/src/PointLight.cs
- Elements/src/SpotLight.cs
- Elements/test/ColorTests.cs
BACKGROUND:
- Colors are fun! 
DESCRIPTION:
- Adds a new Color constructor that takes a string — either a [known color name ](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.knowncolor?view=net-6.0) or a hex code. A corresponding implicit conversion operator is added as well. 
TESTING:
- Several new tests are added.
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/748)
> Color Convenience functions

- Elements/test/Grid2dTests.cs
BACKGROUND:
Warning when running `dotnet test`:
```
Elements\test\Grid2dTests.cs(116,13): warning xUnit2013: Do not use Assert.Equal() to check for collection size.
```
DESCRIPTION:
This PR addresses the xUnit2013 warning.  `Assert.Zero` is used to assert a collection of zero expected elements, `Assert.Single` for asserting a collection of one expected element. https://xunit.net/xunit.analyzers/rules/xUnit2013
TESTING:
The xUnit2013 warning is not displayed when running `dotnet test`
FUTURE WORK:
None anticipated
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/753)
> Fixes xUnit2013 warning

- Elements/src/Geometry/Profiles/ParametricProfile.cs
BACKGROUND:
- On running `dotnet test` the following warning was seen:
```
Elements\src\Geometry\Profiles\ParametricProfile.cs(138,97): warning CS1573: Parameter 'name' has no matching param tag in the XML comment for 'ParametricProfile.SetPropertiesFromProfileData(Dictionary<string, double>, string)' (but other parameters do)
```
DESCRIPTION:
Adds the missing parameter to address the warning
TESTING:
The above mentioned warning is no longer seen after applying this PR
FUTURE WORK:
None anticipated
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/754)
> Adds missing param declaration to docs for SetPropertiesFromProfileData

- CHANGELOG.md
- Elements/src/Geometry/Bezier.cs
- Elements/test/BezierTests.cs
BACKGROUND:
Fixes https://github.com/hypar-io/Elements/issues/462
DESCRIPTION:
When calculating the length of the first segment on the bezier curve, it erroneously used the origin as the start of the curve.  This PR corrects this to use the start point of the bezier curve.
TESTING:
Tests included.
- bezier.Length() should now match polyline.Length() where the number of divisions matches the bezier samples.
FUTURE WORK:
- The linear interpolation method is very approximate.
REQUIRED:
COMMENTS:
- tests make allowance for the approximate method of calculating length.  This is noted as an inline comment within the test code.
- tests comparing bezier.Length() to polyline.Length() may be brittle to changes in samples constant within Bezier.  This is noted as an inline comment within the test …
> Fix `Bezier.Length()`

- Elements/src/Wall.cs
- Elements/src/WallByProfile.cs
BACKGROUND:
When running `dotnet test`, CS0618 warnings were generated for use of Obsolete Wall.Profile and Wall.Height properties; e.g.:
```
Elements\src\WallByProfile.cs(93,13): warning CS0618: 'Wall.Profile' is obsolete: 'The profile property on the Wall base class is obsolete, check the methods of an inherited class like StandardWall or WallByProfile.'
```
DESCRIPTION:
This suppresses the warning without fixing the underlying cause i.e. the obsolete properties continue to be used.
TESTING:
- The warnings, described above, are no longer present when running `dotnet test`
FUTURE WORK:
- It may be possible to remove the root cause of the warnings (i.e. not to use the obsolete properties) rather than suppressing them.
REQUIRED:
- Change log is assumed not required as this does not change …
> Suppress 612 and 618 warnings for Wall properties

- CHANGELOG.md
- Elements/src/ModelLines.cs
- Elements/src/ModelPoints.cs
- Elements/test/ModelLinesTests.cs
BACKGROUND:
- I needed visualization AdaptiveGrid edges. For this, I used ModelPoints plus a set of ModelCurve objects. This slowed web view, especially when zoomed out.
DESCRIPTION:
- Added ModelLines specialized in drawing a set of lines that share material from the single buffer. This means that all the lines, if selectable, are selected together, but the drawing is lag free. 
TESTING:
- Added ModelLinesTest.cs to show simple usage example.
REQUIRED:
- [x ] All changes are up to date in `CHANGELOG.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/760)
> Add ModelLines for visualization of line collection what share material

- Elements/src/Model.cs
BACKGROUND:
- Functions published with latest alphas broke because the function signature of ToJson changed.
- ![image](https://user-images.githubusercontent.com/5872187/151428724-408b193c-0b46-40da-9b0d-83451b1c8870.png)
- the Hypar repo was not updated appropriately 
- Breakage occurred even though signature introduced only arguments with defaults, which should be optional, and the only place it is used used passes no arguments.
DESCRIPTION:
- Add an explicit `ToJson()` method that has no arguments for future compatibility.
TESTING:
- publishing a function with latest alphas will result in error during function execution.
- `dotnet add package Hypar.Elements --version 0.9.9-alpha.7`
- `dotnet add package Hypar.Functions --version 0.9.11-alpha.3`
FUTURE WORK:
- We will update the …
> add a more default model.tojson

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
- When AdaptiveGrid is intersected by a box, all intersected edges were cut and leftover portions were inserted back into the grid. This is not always wanted as "dead end" edges were creating routing issues in some conditions. 
DESCRIPTION:
- Added parameter `removeCutEdges` to `AdaptiveGrid.SubstructBox` that control if cut parts of intersected edges need to be inserted into the graph. The parameter is set to false (old behavior) by default.
TESTING:
- Added test AdaptiveGridSubtractBoxCutEdges and changed test AdaptiveGridSubtractBox (now AdaptiveGridSubtractBoxKeepEdges)
FUTURE WORK:
- In future we might need function that cut space not using global coordinate space but coordinate space of the grid.
REQUIRED:
COMMENTS:
--- …
> Add parameter `removeCutEdges` to `AdaptiveGrid.SubstructBox`

- Elements/src/BaseCeiling.cs
- Elements/src/OpenCeiling.cs
- Elements/src/SolidCeiling.cs
- Elements/src/TiledCeiling.cs
BACKGROUND:
We need new ceilings types for creating ceilings.
DESCRIPTION:
- Add new classes for ceilings: 
- BaseCeiling - the base class for all ceilings.
- OpenCeiling - a ceiling that has no physical geometry, but still defines a perimeter and an elevation
- TiledCeiling - tiled ceiling, which is defined by tile length, width and space between tiles.
- Rename Ceiling class to SolidCeiling
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/766)
> Add new ceilings

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
During creation of documentation for AdaptiveGrid in was discussed that removeCutEdges option was not used and not really needed.
Grid with leftover edges
Grid without leftover edges
Moreover, cut edge code makes function much more complicated.
DESCRIPTION:
- These changes remove extra code needed to support removeCutEdges  = false
TESTING:
- Removed a test for removeCutEdges = true
- Add one test to AdaptiveGridTest not related to the changes
- Add Trait("Category", "Examples") to tests that use model outputs
FUTURE WORK:
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/775)
> Remove removeCutEdges parameter from AdaptiveGrid.SubstructBox

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/test/LineTests.cs
BACKGROUND:
- I found two missing methods in Line API:
- `IsCollinear(Line line)` will check if line is collinear with base line
- `GetOverlap(Line line)` will return line which is a part of both lines, base and line
DESCRIPTION:
- `IsCollinear(Line line)` methods checks if `Direction` vectors are parallel
- `GetOverlap(Line line)` method checks if lines are collinear, then it takes all line ends and order them by sum of their coordinates. When 2nd and 3rd vector lies on both lines they are ends of overlapping line. 
TESTING:
- Run `IsCollinear` and `GetOverlap` unit tests 
FUTURE WORK:
- There is no future work needed 
REQUIRED:
COMMENTS:
--- …
> Line get overlap extension

- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- It's not possible to create polygon from list of vertices where first and last points are equal. In `Polygon` constructor this case is solved, but in base `Polyline` constructor it's not - duplicated last point is not removed and then overridden method `Edges` returns zero length edge and exception is thrown "A segment of the polyline has zero length".
DESCRIPTION:
- Extract vertices validation to virtual method, so the right validation logic will be used for derived classes
TESTING:
- Add `PolygonTests.ConstructWithSequentialDuplicates` test.
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/777)
> Fix polygon creation from vertices with sequential duplicates

- CHANGELOG.md
- Elements/src/Geometry/Bezier.cs
- Elements/src/Geometry/Curve.cs
- Elements/src/Geometry/Mesh.cs
- Elements/src/Geometry/MeshPrimitives.cs
- Elements/src/Geometry/Meshes.cs
- Elements/test/ArcTests.cs
- Elements/test/BezierTests.cs
- Elements/test/Grid1dTests.cs
- Elements/test/MeshPrimitivesTests.cs
BACKGROUND:
- Having some mesh primitives like spheres and cubes is useful for various tasks.
DESCRIPTION:
- This PR adds the `Mesh.Sphere` method to create a mesh sphere.
- This PR fixes the `ToPolyline` method, which was creating polylines that were one segment short of the end of the curve being converted. It then also fixes all tests where `ToPolyline` is excercised, and adds tests to ensure that polylines created in this way align with the start and end points of curves.
REQUIRED:
Use the `divisions` parameter to change the precision.
Example 10
Example 50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/778)
> Mesh sphere

- Elements/src/Geometry/Polygon.cs
BACKGROUND:
Some models exported from Revit couldn't be opened in JSON to Model function. It happens when polyline contains three points A, B and C: 
AB == BC
DESCRIPTION:
This PR contains additional check: if point AB overlapping BC and C==A, delete B and C;
TESTING:
I can provide json model. JSON to Model function is already published to dev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/780)
> Added additional check to DeleteVerticesForOverlappingEdges

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Vector3.cs
- Elements/test/LineTests.cs
BACKGROUND:
When working with walls that belong to several rooms I realized that some wall that were shared between two rooms were not correctly identified. 
I have found two issues in Elements:
- `Vector3.AreCollinear(Vector3 a, Vector3 b, Vector3 c)` was returning `false` if two points are coincident but not exactly.
Checking IsZero after normalizing is not efficient when two points are almost coincident. In this case even slightest variation between two points start to dominate.
- `Line.TryGetOverlap(Line line, out Line overlap)` would return incorrect results due to wrong internal sorting.
DESCRIPTION:
- In `Vector3.AreCollinear` do IsZero check before normalization.
- In `Line.TryGetOverlap`, since it works on collinear lines, use dot product sorting.
TESTING:
- Added extra test …
> Fixes for Vector3.AreCollinear and Line.TryGetOverlap

- CHANGELOG.md
- Elements.CodeGeneration/src/TypeGenerator.cs
- Elements/src/Floor.cs
BACKGROUND:
- This PR works in tandem with https://github.com/hypar-io/Hypar/pull/465.
- In complex scenarios, code generation would not exclude all types it was expected to. For example:
Type `CirculationSegment`'s schema has it extend `Floor`. We were only checking top-level types from `element_types` against known types, so a `Floor.g.cs` still got created, breaking compilation.
- A function containing within its `element_types` a schema (like `CirculationSegment`) which refers to a type like `ThickenedPolyline` which can ALSO be a input type would result in dual generation of that type: `Elements.ThickenedPolyline` and `Circulation.ThickenedPolyline` in the `Inputs` class, and one could not be converted to the other. 
DESCRIPTION:
- Adds more opportunities to inject a `HashSet` of …
> better support for excluding types from codegen

- CHANGELOG.md
- Elements/src/PriorityQueue.cs
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/src/Spatial/AdaptiveGrid/Edge.cs
- Elements/src/Spatial/AdaptiveGrid/Vertex.cs
- Elements/test/AdaptiveGraphRoutingTests.cs
- Elements/test/AdaptiveGridTests.cs
- Elements/test/PriorityQueueTests.cs
BACKGROUND:
- While working on new function that used AdaptiveGrid I collected all pieces of code related to AdaptiveGrid but located outside Elements. It make sense to place them directly into
- It was decided to move AdaptiveGraph routing and PriorityQueue into Elements as whey had no collections with previous repository.
DESCRIPTION:
- Remove AdaptiveGrid reference from Edge and Vertex to make it independent. Move Edge.GetVertices and Edge.GetLine to AdaptiveGrid.
- Add Vertex.GetEdge, Edge.OtherVertexId.
- Add default constructor to AdaptiveGrid to avoid manual creation of new Transform object.
- Add AdaptiveGrid.AddVertexStrip for adding connected chain of vertices.
- Add AdaptiveGrid.CutEdge for replacing an edge with two new edges that meet at given point.Point.
- Add …
> Adaptive Grid update

- Elements.Serialization.IFC/src/Serialization/IFC/IFCElementExtensions.cs
BACKGROUND:
Beams elements were not created as ifcBeam
DESCRIPTION:
- Fixed ToIfc syntaxes 
- Added 'else' after 'is Beam' check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/799)
> Small fixes

- Elements.Benchmarks/ElementCreation.cs
- Elements/src/ContentCatalog.cs
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Polyline.cs
- Elements/src/Model.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/src/Validators/Validator.cs
BACKGROUND:
- There were some annoying warnings when building —"obsolete" warnings and missing XML comments.
DESCRIPTION:
- Fixes a typo
- adds `#pragma` ignores for valid uses of obsolete apis 
- adds XML descriptions for methods that lacked them
REQUIRED:
- [N/A] All changes are up to date in `CHANGELOG.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/802)
> fix up warnings, typos

- CHANGELOG.md
- Elements/src/GeometricElement.cs
- Elements/src/Geometry/Curve.cs
- Elements/src/Geometry/Vector3Extensions.cs
- Elements/src/GridLine.cs
- Elements/src/ModelArrows.cs
- Elements/src/ModelCurve.cs
- Elements/src/ModelLines.cs
- Elements/src/ModelPoints.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/test/GeometricElementTests.cs
BACKGROUND:
- Users may want to create custom types that specify their own buffer logic. Previously this was only possible for types within Elements.
DESCRIPTION:
- Exposes `TryToGraphicsBuffers` and `ToGraphicsBuffers` APIs as public
- simplifies `ToGraphicsBuffers`. It appears it was doing some unnecessary index manipulation to mimic the behavior of  `GL_LINE_LOOP` — but since we exposed setting the Mode (in #704, I think?), this is no longer needed.
TESTING:
- I checked the GLB output of 
- `GridLine`
- `ToGLTF()` with `drawEdges`=`true`
- other `ModelCurve` tests producing both open and closed curves
- `ModelLines`
and verified it was visually unchanged
FUTURE WORK:
- `ToGLTF()` with `drawEdges`=`true` appears somewhat broken. It only works right now for element instances. 
REQUIRED: …
> Make TryToGraphicsBuffers public

- Elements.CodeGeneration/src/Templates/Class.liquid
BACKGROUND:
- CodeGen of enums would sometimes result in invalid C# code. Even though we have `using Newtonsoft.Json` in the class template, because we didn't have `using Newtonsoft.Json.Converters`, this would not build.
DESCRIPTION:
- fully qualifies `Newtonsoft.Json.Converters.StringEnumConverter`
TESTING:
- I tested this with a local build of the Hypar CLI which references this version of elements, and verified that string enums no longer generated invalid code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/807)
> fix for string enum codegen

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/test/LineTests.cs
BACKGROUND:
I found `Line.Projected(Plane plane)` useful and missing in `Line` class
DESCRIPTION:
Method `Line.Projected(Plane plane)`  projects `Start` and `End` vectors onto `Plane`. After that it creates new `Line` with projected vectors.
TESTING:
FUTURE WORK:
None 
REQUIRED:
COMMENTS:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/811)
> Add Project method to Line

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/test/LineTests.cs
BACKGROUND:
I found `MergeCollinearLine(Line line)` method useful and missing in `Line` class 
DESCRIPTION:
Method `MergeCollinearLine(Line line)` takes all 4 vertices of two lines, sort them and creates line which contains all of them. Finally it keeps direction of original line.
TESTING:
Since there are many similarities to `TryGetOverlap(....)` method I reused unit test cases.  
FUTURE WORK:
None
REQUIRED:
COMMENTS:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/810)
> Line merge collinear line

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/test/LineTests.cs
BACKGROUND:
I found `GetUParameter()` method useful and missing in `Line` class. 
DESCRIPTION:
`GetuUParameter` checks if point is on line. If not it returns -1, otherwise it returns U parameter.
TESTING:
FUTURE WORK:
None
REQUIRED:
COMMENTS:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/809)
> Line GetUValue for point on line

- Elements.CodeGeneration/src/TypeGenerator.cs
- Elements.Serialization.IFC/src/Serialization/IFC/IFCElementExtensions.cs
- Elements.Serialization.IFC/src/Serialization/IFC/IFCModelExtensions.cs
- Elements/src/Floor.cs
BACKGROUND:
New types that are inherited from Floor or some other types are exported to the IFC as Objects and are not recognized as Floor or Beam elements. The issue is that during json deserialization inside Exporter class, Exporter generates new classes from schema (e.g. FloorPanal) without inheritance from the Floor class 
DESCRIPTION:
- This PR includes all locally loaded types to the CSharpGeneratorSettings.ExcludedTypeNames. That allows to create proper inheritance. 
TESTING:
I tried:
- generate IFC
- CLI init command
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/815)
> Loaded types

- CHANGELOG.md
- Elements/src/TiledCeiling.cs
DESCRIPTION:
- Add GetTileCells method to TiledCeiling, that returns all tile cells of ceiling as Grid2d
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/826)
> Add GetTileCells method to TiledCeiling

- CHANGELOG.md
- Elements/src/Geometry/Solids/Edge.cs
- Elements/src/Geometry/Solids/Vertex.cs
BACKGROUND:
I wanted to optimize performance and use `Elements.Geometry.Solids.Edge` class instead of `Line`, unfortunately there is not any public constructor for it. 
DESCRIPTION:
Change `Elements.Geometry.Solids.Edge` and `Elements.Geometry.Solids.Vertex` constructors from internal to public.
TESTING:
FUTURE WORK:
No additional work is required 
REQUIRED:
COMMENTS:
There isn't any
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/833)
> Public Edge and Vertex constructors 

- CHANGELOG.md
- Elements/src/Geometry/Transform.cs
- Elements/test/TransformTests.cs
BACKGROUND:
- Our rotate methods for transforms can be counter-intuitive, if the object you're trying to rotate is already positioned somewhere in space. 
DESCRIPTION:
- adds `RotateAboutPoint` and `RotatedAboutPoint` convenience methods for rotating a transform about a point and axis.
TESTING:
- Added a test to demonstrate.
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/834)
> add RotateAboutPoint method

- CHANGELOG.md
- Elements/src/Geometry/Vector3Extensions.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- The `AreCoplanar` extension method for collections of vertices had an error that caused it to be potentially several orders of magnitude more sensitive to deviation than it was intended to be. Specifically, checking the dot product with the un-unitized cross product meant that the deviation was multiplied by the area of the parallelogram between the first two edges, which could be quite a large number, effectively tightening the tolerance of the method.
DESCRIPTION:
- Fixes the error and adds a test
TESTING:
- A new test deserializing a polygon with a deviation in the z of 6.3e-7 is added
- All other tests are passing
FUTURE WORK:
REQUIRED:
--- …
> Fix tolerance for AreCoplanar

- CHANGELOG.md
- Elements/src/Beam.cs
- Elements/src/Column.cs
- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Vector3.cs
- Elements/src/StructuralFraming.cs
- Elements/test/LineTests.cs
- Elements/test/ProfileTests.cs
BACKGROUND:
Vector3.PointOnLine is based on dot product and because of that answer is angle based. The longer the line is - the bigger deviation is allowed. For example Line((0, 0, 0), (150, 0, 0) will return true for (100, 0.1, 0) point that can lead to unwanted results.
Because how includeEnds parameter is coded it's unclear what it means: when it's false exactly end point will always return true, but when numeric noise is present: (1e-6, 0, 0) will return True for the line above but (1e-6, 1e-6, 0) will return false.
DESCRIPTION:
PointOnLine is now distance based and is based on calculations from Vector3.DistanceTo(Line): return true if point is less than tolerance away from the line.
New implementation is not using Sqrt so it's quicker than old one although it uses extra checks.
New …
> Change Line.PointOnLine

- CHANGELOG.md
- Elements/src/Search/DoubleToleranceComparer.cs
- Elements/test/DoubleToleranceComparerTests.cs
BACKGROUND:
- AdaptiveGrid needed a way to group items by Z coordinate within certain tolerance.
DESCRIPTION:
- Added DoubleToleranceComparer that treats all numbers within tolerance as the same.
This comparer doesn't use hash code as it is *impossible* to create a hashing algorithm that consistently returns identical values for any two points within tolerance of each other.
Note that any item that is not within tolerance of other key is set as a new key.
This mean that keys are not always whole number in the middle of a range.
TESTING:
- Added DoubleToleranceComparerTests test.
REQUIRED:
COMMENTS:
- These is Vector3Comparer class that is similar but it uses GetHashCode that make it volatile in behavior. It may be considered to make it also always use 0 as hash code.
---
This change …
> Add DoubleToleranceComparer

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/test/LineTests.cs
BACKGROUND:
I didn't find method that checks if particular line lays on plane.
DESCRIPTION:
The method checks distance of `Line.Start` and `Line.End` to `Plane`. If all distances are approximately 0, it means that line lays on plane. The method has optional tolerance parameter. 
TESTING:
FUTURE WORK:
None
REQUIRED:
COMMENTS:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/840)
> Add Line IsOnPlane method

- CHANGELOG.md
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
I didn't find method that will check if provided `Polyline` intersects with other `Line` 
DESCRIPTION:
Method goes through all segments of `Polyline` and checks if line intersects with it. It has all optional parameters which has `Line.Intersects(...)` method
TESTING:
FUTURE WORK:
None
REQUIRED:
COMMENTS:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/844)
> Add Polyline Intersects method

- CHANGELOG.md
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
I didn't find method that will calculate U parameter for a point on polyline
DESCRIPTION:
Methods calculates U parameter for a point on polyline. When output of `Polyline.GetParameterAt()` method is used as an input for method `Polyline.PointAt()` it returns the same point.
TESTING:
FUTURE WORK:
None
REQUIRED:
COMMENTS:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/843)
> Add GetParameterAt method to polyline 

- CHANGELOG.md
- Elements/src/ImportMeshElement.cs
- Elements/src/MeshElement.cs
- Elements/test/BBox3Tests.cs
- Elements/test/MaterialTests.cs
- Elements/test/MeshElementTests.cs
- Elements/test/MeshPrimitivesTests.cs
- Elements/test/TopographyTests.cs
BACKGROUND:
- A user wanted to create a new element that inherited from MeshElement.  They did this with a schema so their constructor was code generated, and this revealed that MeshElement's constructor was not configured correctly to be compatible with code gen.
DESCRIPTION:
- modify the constructor of MeshElement to be compatible with the constructor signature expected by code gen.
TESTING:
- This schema will code gen, and be invalid unless you reference a local elements of this branch.
```
{
"$id": "https://hypar.io/Schemas/CivilSurface.json",
"$schema": "http://json-schema.org/draft-07/schema#",
"description": "A beam.",
"title": "specialMesh",
"x-namespace": "Elements",
"type": [
"object",
"null"
],
"allOf": [
{
"$ref": "https://prod-api.hypar.io/schemas/MeshElement"
}
], …
```
> Make mesh code gen compatible

- CHANGELOG.md
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
I found two bugs in `Polyline.Intersects(Line line ....)` method. 
- On L-shape polygons, method returns results outside of polygon perimeter when infinite flag is set true.
- Method returns duplicated points for lines which share vertices with polygon 
DESCRIPTION:
First bugfix checks if calculated intersection point actually lies on polyline 
Second bugfix checks if calculated intersection point hasn't already been added to list of results.
TESTING:
I added unit tests which reproduce bugs
FUTURE WORK:
None 
REQUIRED:
COMMENTS:
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/847)
> Polyline Intersects line bugfixes 

- CHANGELOG.md
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
- Fixes #855 
DESCRIPTION:
- There were several bugs in `Polyline.NormalsAtVertices` and `Polyline.CreateOrthogonalTransform` resulting in inconsistently-oriented transforms. These have been resolved.
TESTING:
- I added a new test which failed on `master` and passes now — here are the results:
Before:
After: 
I also verified that sweeps of non-planar polylines still looked sensible: 
And visually verified other tests relying on Sweeps (which call this code):
And verified consistency with `Frame` methods for other curves, and polyline's `TransformAt` method:
FUTURE WORK:
- We should consider implementing a canonical "Rotation Minimizing Frame" here instead of inventing our own. See https://github.com/GSharker/G-Shark/blob/69d2286e38b6d928298329646759e69e1776cfa2/src/GShark/Exten …
> Fix Polyline Frame consistency

- CHANGELOG.md
- Elements/src/Annotations/Message.cs
- Elements/src/Annotations/MessageSeverity.cs
- Elements/src/Annotations/Messages.cs
BACKGROUND:
- We want to create messages that exist in space and contain information for users.
DESCRIPTION:
- Create the Messages class as well as some corresponding creation utilities.
- Add the concept of Severity to a message and support varying colors for the messages.
TESTING:
- This workflow has a function called "WarningsWarnings!!" that uses this version of elements to experiment with the new message type.
FUTURE WORK:
- Messages should not be GeometricElements forever.  This is a temporary measure to start standardizing, but we hsould improve the behavior and make them more "Annotation-like".
REQUIRED:
COMMENTS:
- - - …
> add message class and helper creation methods

- CHANGELOG.md
- Elements/src/Geometry/BBox3.cs
BACKGROUND:
- It's a useful feature outside the assembly. I'm going to use it inside Revit converters to create aggregated bounding box for all elements inside view 
DESCRIPTION:
- Changed BBox3.Extend access modifier to public
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/861)
> Changed BBox3.Extend access modifier to public

- Elements/src/Geometry/Line.cs
BACKGROUND:
- Line cannot be created if `points` contain duplicated points
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/856)
> Fix Line.Bestfit error when there are duplicated points

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/src/Spatial/AdaptiveGrid/Obstacle.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
It was notified that after last big changes to AdaptiveGrid that new Obstacle object is not always cut correctly:
- When grid is rotated, obstacle created from box was too small in one dimension.
- When grid boundary has elevation, parts of obstacle were incorrectly treated as outside,
DESCRIPTION:
- Use all corner points of the box to define obstacle instead of just min and max points.
- Make boundary check always done in 2d, don't do any checks if boundary is null.
TESTING:
- Added new tests to AdaptiveGridTests: AdaptiveGridSubstructRotatedBox and BrokenSubtractionForMisalignedPolygon
- Added WriteToModelWithRandomMaterials helper function that writes result to model and can automatically get calling function name.
FUTURE WORK:
- We might want to investigate why …
> Obstacle fix

- CHANGELOG.md
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
I found that `Polyline.Intersects(Polygon polygon, out List<Polyline> sharedSegments)` returns wrong results when polyline start or end is on polygon perimeter.
DESCRIPTION:
I set `includeEnds` flag to true, when methods collects intersections between polygon segments and polyline. I had to add filtering of the same vectors for case polyline intersects with polygon vertex. 
TESTING:
Run unit test 
FUTURE WORK:
None
REQUIRED:
COMMENTS:
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/868)
> Polyline intersects Polygon bug

- CHANGELOG.md
- Elements/src/Annotations/Annotation.cs
- Elements/src/Annotations/IOverrideLinked.cs
- Elements/src/Annotations/LinearDimension.cs
BACKGROUND:
- To support intuitive geometric override editing, we want to support "editable dimensions" for objects. 
DESCRIPTION:
- Adds special metadata to `LinearDimension` objects by way of an `IOverrideLinked` interface. If this data is present, the Hypar web UI treats these dimensions differently (see corresponding PR).
TESTING:
- I created a test function (Editable Dimensions Example) here: `workflows/0e49a6cf-bcf6-4ce8-b80f-382b3ee2d388` (Note that this requires the corresponding Explore branch or sandbox: https://github.com/hypar-io/Explore/pull/2405)
- See also usage example here: https://github.com/andrewheumann/EditableDimensionsExample
FUTURE WORK:
- We may want other kinds of special behaviors for other classes of annotations in the future.
REQUIRED:
COMMENTS:
- In general …
> add support for override-linked dimensions

- Elements/src/Spatial/AdaptiveGrid/Obstacle.cs
BACKGROUND:
When I was working on `Obstacle` changed bahaviour of an Obstacle object. When Points property is accessed I returned points list with offset applied, unfortunately `AdatpiveGrid.SubtractObstacle` uses Points without offset and adds it during subtract.
DESCRIPTION:
Return Points list without any offset
TESTING:
FUTURE WORK:
In future `AdatpiveGrid.SubtractObstacle` can use Obstacle `Intersects` methods 
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/880)
> Bugfix: remove offset from obstacle points

- Elements.Playground/App.razor
- Elements.Playground/Compiler.cs
- Elements.Playground/ElementsAPI.razor
- Elements.Playground/README.md
- Elements.Playground/_Imports.razor
- Elements.Playground/serve.py
- Elements.Playground/serve.sh
- Elements.Playground/wwwroot/index.html
- Elements.Playground/wwwroot/js/elements.d.ts
- Elements.Playground/wwwroot/js/elements.js
BACKGROUND:
- I had to make some adjustments to the `wasm` branch to support calling it from Hypar's front-end. 
DESCRIPTION:
- I removed the Blazor Router, which was getting confused when being called from e.g. `localhost:8080/workflows/{id}`, and just return the elements API component directly
- I changed the `Globals` object to take a JSON string, instead of a dictionary.
- I updated the `Run` operation to return the model json
- I added a `serve` script for use during local Elements development.
TESTING:
- I tested this by building and deploying (a version that ALSO had branch `stj-ah` merged in, in case it matters) to S3, and building an explore sandbox that calls into this code. I verified I could compile and run custom elements code.
- - - …
> playground explore fixes

- CHANGELOG.md
- Elements/src/Serialization/glTF/GltfBufferExtensions.cs
- Elements/test/ContentTests.cs
BACKGROUND:
- A contributor noticed that they were not getting valid models produced by one of the functions when running a recent elements alpha.  It seemed to only occur in a function with content.
DESCRIPTION:
- The index incrementing for merged buffers was wrong, creating invalid buffer view accessors.
TESTING:
- you can run the content test "IsntanceContentElement" that produce glbs.  Included are the before and the after.  Before this change the glb cannot be opened.
[InstanceContentElement.zip](https://github.com/hypar-io/Elements/files/9480186/InstanceContentElement.zip)
FUTURE WORK:
- ~Is there any future work needed or anticipated?  Does this PR create any obvious technical debt?~
REQUIRED:
COMMENTS:
- - - …
> Fix buffer merging

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/Obstacle.cs
- Elements/test/ObstacleTests.cs
BACKGROUND:
- One of our functions was failing after being published with the latest version of Elements.
DESCRIPTION:
- Change the order of vertex addition when creating a polygon from a wall.
- Add tests to catch this and confirm some basic obstacle behavior.
- bunch of whitespace linting
TESTING:
- Tests run
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/884)
> Obstacle wall creation bug

- CHANGELOG.md
- Elements/src/GeometricElement.cs
- Elements/src/Model.cs
BACKGROUND:
The logic for intersection of a `Plane` and a `GeometricElement` should live in `GeometricElement`. 
DESCRIPTION:
This PR refactors intersection logic for a `Plane` and a `GeometricElement` into `GeometricElement.Intersects(...)`. Often, when testing for intersections it's useful to first check the bounds of the geometric element first, so the `Bounds` property is exposed (but not serialized). Finally, the internal computation of a CSG, used to create the bounds, now allows the user to pass through a flag indicating whether the element's transform should be used to compute the CSG, and correspondingly, the bounds.
REQUIRED:
COMMENTS:
- - - …
> Refactor `Plane` intersection into `GeometricElement`.

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/src/Search/BinaryTree.cs
- Elements/src/Search/BinaryTreeNode.cs
- Elements/src/Search/LeftMostPointComparer.cs
- Elements/src/Search/Network.cs
- Elements/test/NetworkTests.cs
BACKGROUND:
Our `Network` provides a basic traversal method that allows you to provide a traversal function. In several locations we have implemented traversal functions to find closed regions in the graph. This is useful when you have a collection of linear elements like walls or grids and want to find enclosed areas like rooms or structural bays.
DESCRIPTION:
- Changes the `LeftMostPointComparer` used by the `BinaryTree` in the line sweep algorithm to improve coincident point handling.
- Adds the `FindAllClosedRegions` method to the `Network` class to find closed regions without having to implement your own traversal strategy.
REQUIRED:
See all the closed regions for a graph with lines 
- - - …
> Find all closed regions in a network.

- CHANGELOG.md
- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- Normally, we don't add elements that are `IsElementDefinition=true` to the GLTF model. However, in the case that a type did create 
DESCRIPTION:
- blocks adding `IsElementDefinition=true` elements to the GLTF via the `TryToGraphicsBuffers` pathway.
TESTING:
- I tried making a function (Residential Units) that was creating instances of `ModelLines`. I verified that the instances did display but the base definition did not.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/891)
> don't create graphics buffers for element definitions

- CHANGELOG.md
- Elements/src/Geometry/Profile.cs
- Elements/test/ProfileTests.cs
BACKGROUND:
- Fixes #877 
DESCRIPTION:
- Forces split profiles to be counter-clockwise wound, since the code measures rotation angle relative to positive Z. 
TESTING:
- I added a new test from user code, and verified it produced the expected results. 
FUTURE WORK:
- We might want to figure out an average `Normal` for the profiles and feed that as the normal to the polygonizer, so we can respect the input winding. But in the case that some profiles are CW, and some are CCW, it's not clear what the algorithm should do. 
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/878)
> fix splitting of clockwise profiles

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/src/Spatial/AdaptiveGrid/Obstacle.cs
- Elements/test/AdaptiveGraphRoutingTests.cs
- Elements/test/AdaptiveGridTests.cs
- Elements/test/ObstacleTests.cs
BACKGROUND:
- After few iteration of changes in AdaptiveGrid and AdaptiveGraph routing. Regressions and inconveniences were found during testing of different workflow.
DESCRIPTION:
- Done 2 fixes in newly updated AdaptiveGrid/Obstacle.
- `AdaptiveGrid.AddVertices` with `ConnectCutAndExtend` how extends only up to `HintExtendDistance` distance.
- Add HintSnapDistance with default value of 3
- Rename AddExtendVertices into AddVerticesWithCustomExtension, add a extendDistance parameter to it and make it public
- Created EdgeInfo structure in AdaptiveGraphRouting instead of a value pair. Added `HasVerticalChange` parameter to it. Is used to do not modify turn cost if either of two edges in turn point is not horizontal.  This prevents "free to travel" loops under 2d hint lines.
TESTING:
- …
> Routing Fixes

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/BranchSide.cs
- Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs
- Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs
- Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs
- Elements/src/Spatial/AdaptiveGrid/RoutingVertex.cs
- Elements/src/Spatial/AdaptiveGrid/TreeOrder.cs
- Elements/test/AdaptiveGraphRoutingTests.cs
BACKGROUND:
- BuildSpanningTree is building a route in two stages. First to the closest hint line and then to the exit. This causes inefficient path in some cases but also makes function slower and harder to understand in general.
- There were other refactoring requests that are done here.
DESCRIPTION:
- Moved `EdgeInfo`, `BranchSide`, `RoutingVertex`, `RoutingConfiguration`, `RoutingHintLine`, `TreeOrder` from `AdaptiveGraphRouting` to their own files.
- Removed concepts that were not used: Guides from RoutingVertex. BuildSpanningTree functions use only single `tailPoint` now.
- BuildSpanningTree functions are greatly simplified. They call ShortestBranchesDijkstra only once per input vertex now. This improves performance, make things easier to understand and behaves better in some 3D …
> AdaptiveGraphRouting simplification

- CHANGELOG.md
- Elements/src/Geometry/Vector3Extensions.cs
- Elements/test/VectorTests.cs
BACKGROUND:
Very often I had to filter vectors list of those which are at the same places. Unfortunately I cannot use `Vector3Comparer` with LINQ `Distinct` method, because it uses `GetHashCode` to determine equality.
DESCRIPTION:
I added new extension method which iterates through list of vectors and checks if any of similar vector is already in list.
TESTING:
Run unit tests
FUTURE WORK:
None
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/895)
> Add extension method RemoveVectorsAtSamePlace

- CHANGELOG.md
- Elements/src/Geometry/Tessellation/Tessellation.cs
BACKGROUND:
- When using elements library and in debug mode geometry generation can be very slow because we get a load of logging about vertex management.  
DESCRIPTION:
- Make the logging of vertex data an explicit flag that needs to be set, intended for use while debugging.
TESTING:
- When using elements in a test for example this should change the default behavior so that it doesn't show all of these logs.
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/897)
> Make vertex console writing optional

- CHANGELOG.md
- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
I found bug in `Polyline.Intersects(Polygon polygon, out var sharedSegments)` when there was odd number of intersections between polyline and polygon. 
I found also useful to revert output polyline direction when method input parameters are reversed.
DESCRIPTION:
In `Polyline.Intersects` method I was processing intersections in pairs, but when there was odd number of them, it led to wrong output. I fixed it by processing each intersection with following one. I also used `UniqueWithinTolerance()` extension method for  filtering vectors close to each other within tolerance.
Previously `GetSubsegment` method kept direction of `Polyline`. Now it will always traverse from start `Vector3` to end `Vector3` and will return path of that traverse.
TESTING:
FUTURE WORK:
- …
> Polyline Intersects bug and GetSubsegment behavior change

- Elements/src/extension.dib
BACKGROUND:
- I use DotNet interactive notebooks frequently when prototyping function code. We published a set of helpers in #745 
which make it easy to visualize geometry in notebooks.
DESCRIPTION:
- Expands our existing helpers to support:
- Modifying the default size of the model view
- returning Curve, Profile, or Element objects directly and seeing them visualized
- returning collections of Curve, Profile, or Element objects and seeing them visualized 
TESTING:
- I tested by copying and pasting the "Extension" code directly into a notebook, adjusting the default sizes, and returning various object types
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/904)
> add additional helpers for model display in notebooks

- Elements/src/extension.dib
BACKGROUND:
- In the interest of being able to support quick visual debugging, I've made a few more tweaks to the extension code that loads when you load `Elements` into a dotnet interactive notebook. Specifically, there was an issue where the camera would get "locked" if you produced a model with only 3d geometry. 
DESCRIPTION:
- Fixes the "lock" problem by removing the controls' "max distance"
- Sets the camera to automatically choose a top view if the geometry in the model is flat on the XY plane
- enables setting of the default curve display material
- adds a few more convenience imports
TESTING:
- You can copy-paste the contents of the `extension.dib` file into another notebook to see how it would behave — effectively this .dib just gets loaded / run automatically when you load the …
> More notebook tweaks

- Elements/src/Spatial/Grid1d.cs
- Elements/test/Grid1dTests.cs
BACKGROUND:
When constructing a fully defined Grid1d pattern (no excess), it's easy to create a situation where numerical imprecision causes the sum of the length of all segments to be slightly higher than the full grid length.
DESCRIPTION:
Uses tolerance when validating patterns, and rounding very small remainders to zero.
TESTING:
See add unit test `PatternWithinEpsilonOfLengthDoesNotThrowException`.
REQUIRED:
- [✓] All changes are up to date in `CHANGELOG.md`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/907)
> Grid1d should tolerate patterns that are within an epsilon of grid length

- Elements/src/Geometry/Arc.cs
- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Polygon.cs
- Elements/src/Geometry/Polyline.cs
- Elements/test/ArcTests.cs
- Elements/test/LineTests.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- `PointAt` methods throw an exception when `u` parameter is almost equals 0 or 1, but not exactly inside these bounds, such as -6e-15
DESCRIPTION:
- Validates the `u` parameter in `PointAt` methods to be between 0 and 1 with tolerance
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/903)
> Validate the u parameter in PointAt methods with tolerance

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/test/AdaptiveGridTests.cs
- Elements/test/VectorTests.cs
BACKGROUND:
- AdaptiveGrid routing requires more 3D oriented tools for manipulation. One is to be able to duplicate edges from one plane and create another one.
DESCRIPTION:
- Added SnapshotEdgesOnPlane and InsertSnapshot to AdaptiveGrid.
- Using Plane and Transform allow having different configurations.
- Pair of Vector3 is used so snapshot is valid even if some edges are removed between storing and inserting a duplicate.
TESTING:
- Added AdaptiveGridStoreAndDuplicateElevation test.
FUTURE WORK:
- Add support of 3D hint lines.
REQUIRED:
COMMENTS:
- Added AdaptiveGridSubtractBoxAddPerimeter that was not submitted last time by mistake.
- Added test case to DistanceToPlane test making sure it works with non zero origin.
- - - …
> Add layer duplication functions to AdaptiveGrid.

- CHANGELOG.md
- Elements/src/Geometry/Plane.cs
BACKGROUND:
- I wind up re-creating the XY plane all over my code all the time. it should just be available like Vector3.XAxis etc.
DESCRIPTION:
- Adds built-in static planes for XY, YZ, and XZ.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/894)
> add xy, yz, and xz default planes

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Polygon.cs
- Elements/test/LineTests.cs
- Elements/test/PolygonTests.cs
BACKGROUND:
- I needed several geometric operations to be "fuzzier."
DESCRIPTION:
- `Line.IsCollinear` - added `tolerance` parameter.
- `Polygon.CollinearPointsRemoved` - added `tolerance` parameter.
- `Line.TryGetOverlap` - added `tolerance` parameter.
TESTING:
- I have tested this in a function, and added/updated 3 tests to ensure this works as expected.
FUTURE WORK:
- We should consider making this a "rule" for elements: if a method relies on distance based checks, it should expose its tolerance parameters. (and documenting said rule, eg in the PR template)
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/906)
> Tolerance for several collinearity methods

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs
- Elements/test/AdaptiveGraphRoutingTests.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
- AdaptiveGraphRouting needed support of 3D hint lines for 3D routing.
DESCRIPTION:
Added Is2D property to RoutingHintLine. Based on this property edge factors are calculated in a different way in AdaptiveGraphRouting.
AddVerticesWithCustomExtension always insert vertices to the grid:
- Before, segments where just inserted only if it was "inside" the grid - extended segment must have hit at lest one edge on both sides.
- This is inconsistent with other cases of AddVertices and too confusing.
- Now points are always added to the grid and connected.
- The responsibilities for polyline correctness is shifted to the end user.
TESTING:
Added Add3DVerticesWithCustomExtension and AdaptiveGraphRouting3DHintLineCheck tests.
REQUIRED:
- - - …
> Add 3D hint line support to AdaptiveGraphRouting, AdaptiveGrid and RoutingHintLine

- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
DESCRIPTION:
- Make the polyline correspond to the supported angles by moving the vertices slightly. The result polyline will have only allowed angles, but vertices positions will change.
- For each 3 consecutive points A, B, C to make angle ABC be one of allowed angles:
- NormalizationType.Start: move B vertex
- NormalizationType.Middle: move both B and C vertices in approximately equivalent proportions
- NormalizationType.End : move C vertex
TESTING:
- Added `PolylineForceAngleCompliance`, `PolylineForceAngleCompliance3dPath`, `PolylineForceAngleComplianceWithCollinearPoints` tests to `PolylineTests`
FUTURE WORK:
- This method doesn't always work right for polylines with collinear points. See `PolylineForceAngleComplianceWithCollinearPoints` test
REQUIRED:
- - - …
> Add ForceAngleCompliance method to Polyline

- Elements/src/Geometry/Line.cs
- Elements/src/Spatial/HalfEdgeGraph2d.cs
- Elements/test/LineTests.cs
BACKGROUND:
- There were still some cases where `Lines.Offset` didn't find the correct polygon, and the `GetEdgeList` code was overcomplicated.
DESCRIPTION:
- Simplifies `GetEdgeList` to behave more similarly between Polygon and Polyline. 
TESTING:
- I added several new tests and also tested in a function:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/910)
> simplified polyline offset logic

- CHANGELOG.md
- Elements.CodeGeneration/src/CatalogGenerator.cs
BACKGROUND:
- User in another country reported that content catalogs were being generated with invalid nubmer formatting where `,` is used instead of `.` 
DESCRIPTION:
- Set the current culture to `en-US` so numbers are correctly formatted
TESTING:
- I tested this by setting the culture to one that would create this problem, for example "pl-PL" and seeing that this did indeed affect the outcome, so I presume that it will fix the issue in reverse.
FUTURE WORK:
- Other places in code taht need this same treatment?  it seems like it most places we don't have explicity values for numbers so this isn't really an issue.
REQUIRED:
COMMENTS:
- - - …
> set current culture to en-US so numbers are correct

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/TreeNode.cs
- Elements/test/AdaptiveGraphRoutingTests.cs
BACKGROUND:
- Were reported next issues with AdaptiveGraphRouting.
A) When leaf can connect to the tree in several points with the same cost - random path is chosen.
B) Longer as expected leaf is user for leafs that are connected to the tree first.  
DESCRIPTION:
- Added TreeNode and use it instead of just dictionary. This allows to track leaf/trunk connections in the tree.
- If several connection points on the tree have the same cost, one is chosen that is closer to the end.
- Do additional step of leaf routing. When trunk is constructed leafs can find better connection point. 
- Make decision making for choosing where to connect to the trunk more predictable:
A) Lowest travel cost
B) If same - closest point to the exit
C) From two calculated paths choose the one that has no turn with …
> Add TreeNode and use it for AdaptiveGraphRouting. Do additional step of leaf routing.

- CHANGELOG.md
- Elements/src/Validators/Validators.cs
BACKGROUND:
- A developer had a really tricky bug in a function because of a model failing to deserialize.  They eventually traced it down to a failure  creating a BBox3.  The failure was only because our validator doesn't allow degenerate bounding boxes.  There's no real reason to disallow 0 volume bounding boxes.
DESCRIPTION:
- Remove the BBox3 validator
TESTING:
- Tests are fine.
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/917)
> remove bbox validator

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRoutingWeightModifier.cs
- Elements/src/Spatial/AdaptiveGrid/EdgeFlags.cs
- Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs
- Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs
- Elements/src/Spatial/AdaptiveGrid/WeightModifier.cs
- Elements/test/AdaptiveGraphRoutingTests.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
- Support of 3D routing required more flexible way to set weight modifiers to regions of the grid instead of just main layer and penalty.
DESCRIPTION:
- Added WeightModifier object that hold function that allows to apply factor multiplier to edge travel cost.
If edge passes check of several WeightModifier objects - lowest factor is chosen.
- Added Flags field to EdgeInfo to hold additional information, like is edge used by and hint line, without inflating object size too much.
TESTING:
- Added AdaptiveGraphRoutingWeightModifier test.
FUTURE WORK:
- 3D routing is complex topic so code can still undergo changes.
REQUIRED:
COMMENTS:
- Not sure if we need marking code "Obsolete". Let me know if I just need to remove it.
- - - …
> AdaptiveGraphRouting: add WeightModifier and EdgeInfo.Flags

- CHANGELOG.md
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/test/MaterialTests.cs
BACKGROUND:
When integrating the three gpu path tracer in Hypar, I noticed that materials were overly reflective. After opening https://github.com/gkjohnson/three-gpu-pathtracer/issues/310, I was informed that the extension we have used previously, `KHR_materials_pbrSpecularGlossiness` is being "archived" in favor of newer extensions.
DESCRIPTION:
This PR updates our glTF serialization to support `KHR_materials_specular` and `KHR_materials_ior`, with conversions as noted in https://github.com/donmccurdy/glTF-Transform/blob/d77ca6a12c5b56efa1b6594806450dd38df19b25/packages/functions/src/metal-rough.ts
TESTING:
Run a test and export a glTF file. The results should look very similar. I've exported several glTF's and run them through Don McCurdy's viewer and they pass all validation and look …
> Switch to the metal roughness model for glTF.

- Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj
- Elements.Serialization.SVG/src/SvgDrawingExtensions.cs
This fixes all compiler warnings in the `Elements.Serialization.SVG` project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/923)
> Add documentation in the Elements.Serialization.SVG project.

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
BACKGROUND:
- After recent changes to AdaptiveGraphRouting RenderElements function stopped assigning colors to ModelLine objects.
DESCRIPTION:
- Fix wrong assignment of EdgeFlag flags.
- Removed coloring main/non main layer since main layer is obsolete.
- Instead color user/offset hint lines and and divide regular edges into groups with weights < 1, near 1 and > 1.
TESTING:
- All test are passing.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/924)
> Fix regression in AdaptiveGraphRouting.RenderElements

- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
- During testing of AdaptiveGraphRouting I have found that HasVerticalChanes flag is set incorrecly.
DESCRIPTION:
- Made EdgeInfo.Flags private.
- Fix wrong usage of bit flag in EdgeInfo constructor.
TESTING:
- Failed case is included into EdgeInfoFlagsTest.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/926)
> EdgeInfo.Flags hotfix

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
BACKGROUND:
- After adding weight modifier to vertical edges, highlighted for changing, it was not working as intended, since vertical edge turns weren't discounter. Routing chose to drop whole path to lower elevation instead of lowering at intended point. 
DESCRIPTION:
- Removed rule exception from `AdaptiveGraphRouting.TurnCost` that prevented vertical edges turn cost being discounter. It was not reliable and worked bad with new concept of weight modifiers.
FUTURE WORK:
- If problem of "free to travel" loops under 2d hint lines appears again, new solution should be found.
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/929)
> Removed rule exception from `AdaptiveGraphRouting.TurnCost`

- CHANGELOG.md
- Elements/src/Spatial/Grid1d.cs
- Elements/test/Grid2dTests.cs
BACKGROUND:
- in `Grid2d`, calling `GetCells` would cause `Cells` to be cached, and changes to child grids like `SplitAtOffset` would not correctly invalidate the cached result.
DESCRIPTION:
- Ensures that all child grid changes invalidate the parent grid2d's computed cells. 
TESTING:
- Added a minimal test, and also ran (but did not commit) the example from @serenayl's code.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/931)
> fix GetCells caching

- CHANGELOG.md
- Elements/src/Annotations/Messages.cs
BACKGROUND:
- I needed a way to visualize a warning related to a polyline but there was only a way to do it for a single line. After inspecting the code I realized that one function can handle both line and polyline 
DESCRIPTION:
- Added  `Message.FromCurve`: much simpler function that takes both line and polyline. 
- `Message.FromLine` is set obsolete.
TESTING:
- No test were added as Message class is about representation and not covered by unit tests.
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/932)
> Add `Message.FromCurve` that can take any Curve including Line, Polyline, etc.

- CHANGELOG.md
- Elements/src/Geometry/Mesh.cs
- Elements/test/MeshTests.cs
BACKGROUND:
- Adding the first vertex to a mesh with "merge" on would throw an exception.
DESCRIPTION:
- Fixes the exception.
TESTING:
-Added a new test which failed and now passes.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/936)
> fix mesh merge exception

- CHANGELOG.md
- Elements/src/Geometry/Profile.cs
- Elements/test/ProfileTests.cs
BACKGROUND:
- When editing profiles via overrides in the Hypar web UI, certain configurations result in "illegal" topologies, like infinitely thin triangles, which break the editor. Some examples of these configurations are:
- adjacent profiles that are nearly-but-not-quite aligned
- profiles where one adjacent edge has an intermediate vertex but the other does not
- This is avoided by providing a "clean" set of profiles.
DESCRIPTION:
- Adds a static `Profile.Cleaned` extension method which cleans up a set of profiles into a clean graph which can be edited.
TESTING:
- I added several tests for the method which passed
- I have also been utilizing this method in production in a real hypar function, with good success. I am moving it to elements because I have another function that needs it. …
> Clean profiles

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/RoutingHintLine.cs
- Elements/test/RoutingHintLineTests.cs
BACKGROUND:
- There was a need in being able check if edges influenced by the hint line are part of the final tree.
DESCRIPTION:
- Moved IsAffectedBy and IsNearby from AdaptiveGraphRouting to RoutingHintLine. This was AdaptiveGraphRouting is simpler and RoutingHintLine has new public functions to use.
TESTING:
- Added RoutingHintLineTests with several tests.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/935)
> Add IsAffectedBy and IsNearby to RoutingHintLine public interface

- CHANGELOG.md
- Elements/src/GeometricElement.cs
- Elements/src/ModelCurve.cs
- Elements/src/ModelLines.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/src/Serialization/glTF/NodeUtilities.cs
- Elements/test/GltfTests.cs
BACKGROUND:
- In early days of Elements, the `name` of the object in the GLTF wasn't utilized for anything. Over time, the Hypar front end has evolved to rely on parsing out critical information from the name — specifically, the element Id, and whether or not it is meant to be selectable. 
DESCRIPTION:
- Establishes an ad-hoc gltf extension called `HYPAR_info` which contains information necessary for the hypar front end to connect element data to GLTF mesh objects. 
TESTING:
- I added a test which verifies that the data is written correctly to the GLTF. 
- I have an in-progress `explore` branch which can read this info if it's present. 
REQUIRED:
- - - …
> store ID and selectability in GLTF without relying on `name`

- CHANGELOG.md
- Elements.CodeGeneration/src/CatalogGenerator.cs
- Elements.CodeGeneration/src/HyparFilters.cs
- Elements.CodeGeneration/src/StringUtilities.cs
- Elements.CodeGeneration/src/Templates/Catalog.liquid
BACKGROUND:
- A catalog created from Revit has quotes in the names of the content elements.  We want these to exist after code generation.
DESCRIPTION:
- Add double double quoting logic for strings and liquid templates.
TESTING:
- This catalog has the offending names. https://hypar.io/user-static/9a6a516e-4777-4ef0-be6b-2ca7c710b70b.json 
FUTURE WORK:
- This quoting is different than quotes for non-literal strings, which could cause us headaches in the future, but I think we mostly use string literals in code gen.
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/938)
> use double double quotes for string literals during code gen

- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/test/AdaptiveGraphRoutingTests.cs
- Elements/test/AdaptiveGridTests.cs
- Elements/test/ObstacleTests.cs
BACKGROUND:
- In most of the cases AdaptiveGrid.TryGetVertexIndex was used with AdaptiveGrid.Tolerance as tolerance parameter. And even if you would want to use larger parameter - function applies tolerance for each coordinate and return first point that has all coordinates less than tolerance away, so it's not suitable for bigger tolerances anyway.
DESCRIPTION:
- What does this PR specifically accomplish?
FUTURE WORK:
- To either do so nested dictionary return actual closest point within tolerance or change the internal structure in favor of something like octree.
REQUIRED:
COMMENTS:
I moved changelog from 1.5.0 alpha 0 from 1.4.0 section to 1.5.0 section
- - - …
> Obsolete Tolerance parameter in AdaptiveGrid.TryGetVertexIndex

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/test/AdaptiveGridTests.cs
- Elements/test/ClipperTest.cs
BACKGROUND:
- During my work with AdaptiveGrid I encountered weird errors time to time: two vertices were inserted into the same spot, or I was not able to retrieve the vertex that is there by it approximate coordinates within the tolerance.  
DESCRIPTION:
- AdaptiveGrid.AddCutEdge: provided missing tolerance parameter PointOnLine. It's necessary since non default tolerance is used in AdaptiveGrid. 
- Define AdaptiveGrid.Tolerance as distance tolerance. Set coordinate tolerance as half of tolerance, so sum of deviations is still less than twice the tolerance.
- Rework vertices lookup of AdaptiveGrid. Don't just check the first suitable X/Y coordinate. Go over each suitable coordinate branch until good vertex is found. The complexity stays the same but function is no longer error prone. …
> AdaptiveGrid. Fix tolerances and vertices loopkup.

- Elements/src/Geometry/Polyline.cs
- Elements/test/PolylineTests.cs
BACKGROUND:
- The `ForceAngleCompliance` method didn't work with 0 angle because in `AngleAlignedDistance` zero value was used in denominator 
DESCRIPTION:
- Add special handling for zero angle
TESTING:
- Added `PolylineForceAngleComplianceWithZeroAngle` test to `PolylineTests`
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/943)
> Improve zero angle handling in Polyline.ForceAngleCompliance

- CHANGELOG.md
- Elements/src/Geometry/Kernel.cs
- Elements/src/Geometry/Solids/Extrude.cs
- Elements/test/SolidTests.cs
BACKGROUND:
- For Hypar Space, we rely on a visual trick for our spaces — we turn them inside out, with their normals inwards, so that you only see the faces on the opposite side of the room, and can look through the top to see the furniture, and easily select it. 
- This is presently achieved by manually building a `ConstructedSolid` direct from faces, since `Extrude` has a built-in check to ensure that normals point out. This works fine, but means that we serialize much more data than is needed in the model: we have to store every vertex, edge, and face, which makes the model json heavy. 
DESCRIPTION:
- Adds an optional `Flipped` property, which inverts the normal check when building the extrude. if `Flipped` is true, the profile is flipped w/r/t the extrusion direction, resulting in an …
> add support for flipped extrude

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Vector3.cs
- Elements/test/LineTests.cs
BACKGROUND:
- At one moment I needed a function that calculates distance between two lines. Just taking minimum between endpoints and lines doesn't work in all cases. So, this function was created. At the end of the day was not used but I decided that it may be a good addition to the Elements.
DESCRIPTION:
- Line.DistanceTo(line) compute distance between any two lines, even those that are not on the same plane.
TESTING:
- Added two tests: one with simple handwritten lines, one with complex parametric numbers.
FUTURE WORK:
- Closest point is not returned but there is enough information to do so. There is no clear closest point for several cases of parallel or overlapping lines. I guess the close end point of other line can be returned in this case. Let me know if this is something you …
> Add Line.DistanceTo(Line)

- Elements/src/Floor.cs
BACKGROUND:
- I need to add a `Level` property to the floor schema, so that floors can have relationships to levels.
- This broke codegen code for types which inherit from floor, like `CirculationSegment`, because the constructor positional arguments were wrong. 
DESCRIPTION:
- Adds an additional constructor with arguments that match the ones in the updated schema.
TESTING:
- Haven't tested. If we merge and it's still broken, I will own cleanup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/949)
> Add "Level" property to floor constructor

- CHANGELOG.md
- Elements/src/Element.cs
BACKGROUND:
- even though `Name` can be null, deserialization was failing if it was omitted from the JSON. This was happening sometimes in `Profile`s produced on the Hypar web app.
DESCRIPTION:
- Uses default settings for the `Name` property, instead of `AllowNull`. 
TESTING:
- I tested in a function utilizing this version of elements, making sure it no longer exploded if name was missing. 
FUTURE WORK:
- There's a lot more we can do to make deserialization less fragile.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/951)
> don't break deserialization if the `Name` property is missing.

- Elements/src/Geometry/Solids/Extrude.cs
BACKGROUND:
- In all the rush to get the Flipped property renamed, I missed a spot.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/954)
> oops, missed a rename

- CHANGELOG.md
- Elements/src/Geometry/CsgExtensions.cs
- Elements/src/Geometry/Solids/Face.cs
- Elements/src/Geometry/Solids/Solid.cs
- Elements/src/Geometry/Solids/SolidExtensions.cs
- Elements/src/Geometry/Solids/Vertex.cs
- Elements/src/Geometry/Tessellation/CsgPolygonTessAdapter.cs
- Elements/src/Geometry/Tessellation/CsgTessellationTargetProvider.cs
- Elements/src/Geometry/Tessellation/SolidFaceTessAdapter.cs
- Elements/src/Geometry/Tessellation/SolidTessellationTargetProvider.cs
- Elements/src/Geometry/Tessellation/Tessellation.cs
- Elements/src/Serialization/JSON/SolidConverter.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/test/CsgTests.cs
- Elements/test/SolidTests.cs
- Elements/test/StructuralFramingTests.cs
BACKGROUND:
See #965.
DESCRIPTION:
This PR adds an additional field to the tuple vertex `tag` which makes vertices unique.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/960)
> Increment tag to support multiple similar CSGs.

- CHANGELOG.md
- Elements/src/Search/Network.cs
- Elements/test/NetworkTests.cs
BACKGROUND:
The wall intersections were not created inside some visibly bound areas:
It happens on some E-shaped intersections:
The problem occurs when building a tree. The order of vertexes looks like this:
And the tree traversal with LeftMostPointComparer:
On step 2 the line on the right site is not added, because it's not the leftMost point. On step 3 the bottom line is removed as successor to  upper line. So point 4 is never added to the tree:
The solution is two change events order and change the LeftMost point location for lines || to Y axis:
DESCRIPTION:
- This PR contains changes above and tests with different E-shaped networks
TESTING:
- A added tests
REQUIRED:
- - - …
> Fix: wall intersections where bounded areas are not being created

- Elements/src/Geometry/BoundedCurve.cs
- Elements/src/Geometry/Curve.cs
- Elements/src/Geometry/Interfaces/IBoundedCurve.cs
- Elements/test/ArcTests.cs
- Elements/test/ModelTest.cs
BACKGROUND:
During discussion of of the impact of the changes to curve parameterization in 2.0, @wynged said that it would ease the transition for existing code that uses `PointAt`, if we could have replacement methods like `PointAtNormalized`.
DESCRIPTION:
- Adds `PointAtNormalized` and `TransformAtNormalized`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/972)
> Normalized

- CHANGELOG.md
- Elements/src/Annotations/Messages.cs
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGraphRouting.cs
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/src/Spatial/AdaptiveGrid/EdgeInfo.cs
- Elements/src/Spatial/AdaptiveGrid/RoutingConfiguration.cs
BACKGROUND:
- Since Elements is now in 2.0 alpha stage, it's good opportunity to remove obsolete items, I introduced.
DESCRIPTION:
- `Message`: removed obsolete `FromLine` method.
- `AdaptiveGrid`: removed obsolete `TryGetVertexIndex` with `tolerance` parameter.
- `EdgeInfo`: obsolete attribute is removed from `HasVerticalChange` property.
- `RoutingConfiguration`: removed obsolete `MainLayer` and `LayerPenalty` properties.
TESTING:
- No impact on Elements tests.
FUTURE WORK:
- Removed methods and properties must be removed from downstream repos in order to use Elements 2.0
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/974)
> Remove obsolete entities from Message, EdgeInfo, AdaptiveGrid and AdaptiveGraphRouting

- CHANGELOG.md
- Elements/src/Geometry/Vector3Extensions.cs
- Elements/test/VectorTests.cs
BACKGROUND:
- Our Vector3 coplanarity check failed for certain input that it should have accepted, which was causing immediate failures on deserialization, breaking several functions. 
DESCRIPTION:
- Rewrites the coplanarity check to use a dot product method instead of a triple-product method. The triple-product computes a _volume_, which means there's no sensible way to think about it in terms of `Vector3.EPSILON` — the dot product lends itself nicely to the interpretation of "check that the points are within EPSILON distance of a plane passing through the first three non-coplanar points" 
TESTING:
- I added some tests, including one that would definitely have failed with the old method. 
REQUIRED:
- - - …
> Fix coplanar check

- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
BACKGROUND:
- Revit conversion was failing weirdly because we were searching through `Autodesk.*` types in the app domain for element types. 
DESCRIPTION:
- Allows custom exclusions for the `JsonInheritanceConverter`. 
TESTING:
- I called `JsonInheritanceConverter.ExcludeTypePrefixesFromTypeCache("Autodesk")` and conversion worked again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/978)
> allow custom prefix exclusion

- CHANGELOG.md
- Elements/src/Annotations/Message.cs
- Elements/src/Annotations/Messages.cs
BACKGROUND:
In a conversation about how to show messages in Hypar, we decided to create a `ShortMessage` property on `Message` to allow developers to represent an error with a short message, even a single character like an emoji.
DESCRIPTION:
This PR adds a `ShortMessage` property to `Message`, and adds three static constructors to `Message` which set the short message for various message types to emojis representing information, warning, and error.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/984)
> Add short-hand methods for Info, Warning, and Error

- CHANGELOG.md
- Elements/src/Geometry/Mesh.cs
- Elements/src/Geometry/Triangle.cs
- Elements/src/Topography.cs
- Elements/test/TopographyTests.cs
BACKGROUND:
- There was a request from some customers to support trimming a topography with a profile. The existing Trim method wasn't exactly what was needed, because it:
- left behind a solid rather than just the top surface
- didn't support voids within the projected shape
- mutated the existing topography instead of creating a new mesh
DESCRIPTION:
- adds `Topography.Trimmed`, which returns a new Topopgraphy trimmed by a Profile
- adds `Topography.TopMesh` which returns just the upwards facing portion of the topo without the sides
- Updates `Topography.Trim` to support Profile instead of Polygon 
- Fixes an issue where cloning a mesh would result in incorrect vertex-triangle relationships, due to an oversight in one Triangle constructor
TESTING:
- Added a test which tests all new …
> Topography.Trimmed

- Elements/src/Search/Network.cs
- Elements/src/Search/NetworkCycleCoverage.cs
- Elements/src/Search/NetworkEdge.cs
- Elements/src/Search/NetworkNode.cs
- Elements/src/Search/VisitDirections.cs
BACKGROUND:
- Network.FindAllClosedRegions cannot find all closed regions correctly in some cases.
DESCRIPTION:
- Moved the logic that searches for closed regions from Network.FindAllClosedRegions into a separate class NetworkCycleCoverage.
- Added NetworkNode class that contains both index and position of vertex. It allows to simplify the code significantly.
- Added NetworkEdge class that is similar to LocalEdge class, but is based on NetworkNode and has several additional methods.
- Replaced _adjacencyList with an adjacency matrix based on NetworkNode and NetworkEdge.
- Algorithm stays the same. The tests are not affected by the changes.
TESTING:
- The tests are not affected by the changes.
- Additionally tested on https://hypar.io/workflows/820ea7b7-1bf1-4779-9a6b-20da7dd6c969.
FUTURE …
> Closed regions search refactoring

- Elements/src/Geometry/Arc.cs
- Elements/src/Geometry/BoundedCurve.cs
- Elements/src/Geometry/Interfaces/IBoundedCurve.cs
- Elements/src/Geometry/Line.cs
BACKGROUND:
- Docs for mid weren't quite right.
DESCRIPTION:
- Change docs for IBoundedCurve Mid to reflect that it is the parameter space mid point.
- inheritdoc on BoundedCurve, Arc and line.
TESTING:
- n/a
FUTURE WORK:
REQUIRED:
- ~[ ] All changes are up to date in `CHANGELOG.md`.~
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/997)
> fix docs on mid

- CHANGELOG.md
- Elements/src/Geometry/Arc.cs
- Elements/test/ArcTests.cs
- Elements/test/IndexedPolyCurveTests.cs
BACKGROUND:
- https://github.com/hypar-io/Elements/issues/994
- We want to allow users to construct Arcs with apparently decreasing angle domains, in order to have intuitive control over arc direction.
DESCRIPTION:
- Updates Arc constructors to ensure that `EndAngle` is always greater than `StartAngle`.
TESTING:
- I added a test for every modified constructor, to verify that for any pair of angles A,B, arc(A,B) looked just like arc(B,A), but parameterized in the opposite direction. 
- I added a test to construct an `IndexedPolycurve` containing an arc which runs "clockwise" with respect to its circle / the Z axis, to ensure consistency in direction of the overall polycurve:
- I added a test for issue #994's original complaint, and visually verified that it worked. 
- All tests pass. …
> don't permit arcs to have decreasing angle domains

- Elements/src/Topography.cs
BACKGROUND:
- goldbeck noticed an issue w/ the topography constructor which clones another topo — it would throw if `Elevations` is null, which it can be.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1004)
> topo elevations can be null

- CHANGELOG.md
- Elements.CodeGeneration/src/Templates/Class.Constructor.Record.liquid
- Elements.CodeGeneration/src/TypeGenerator.cs
- Elements.CodeGeneration/src/TypeResolver.cs
- Elements.CodeGeneration/test/TestData/NullableAndNonNullableTypesSchema.json
- Elements.CodeGeneration/test/TypeGeneratorTests.cs
BACKGROUND:
- In the Hypar CLI, we have supported nullable `Color` and `Vector3` values for a while, as of https://github.com/hypar-io/Hypar/pull/403 and https://github.com/hypar-io/Hypar/pull/492. However, we never brought these improvements over to Elements, meaning that it was supported in `input_schema` / `overrides` but not in element schemas. 
DESCRIPTION:
- Moves the Type Generator from `hypar` to `Elements`
TESTING:
- I tested this in tandem w/ `hypar init`, and I also wrote a test to ensure that the correct types are generated. 
FUTURE WORK:
- Once this is in, we should update `Hypar` to use it instead of having duplicated code. 
REQUIRED:
- - - …
> Support `Color?` and `Vector3?` in elements code generation

- CHANGELOG.md
- Elements/src/Geometry/ThickenedPolyline.cs
- Elements/test/ThickenedPolylineTests.cs
BACKGROUND:
- The Hypar front end supports the concept of a "Thickened Polyline," which is used for wall + corridor drawing. Until now, we've relied on a schema type, and had to ship around a separate library to reproduce the "thickening" behavior that takes place on the client — but now that this type has settled into usefulness, it should get a place in Elements.
DESCRIPTION:
- Adds the `ThickenedPolyline` class. 
TESTING:
- Several tests were added, including an example for docs.
- I have also been using this code extensively in existing projects (https://github.com/hypar-io/function-Circulation/), so trust its behavior.
REQUIRED:
- - - …
> Thickened polylines

- CHANGELOG.md
- Elements/src/Geometry/Arc.cs
- Elements/src/Geometry/Bezier.cs
- Elements/src/Geometry/Circle.cs
- Elements/src/Geometry/Curve.cs
- Elements/src/Geometry/Ellipse.cs
- Elements/src/Geometry/EllipticalArc.cs
- Elements/src/Geometry/IndexedPolycurve.cs
- Elements/src/Geometry/InfiniteLine.cs
- Elements/src/Geometry/Interfaces/ICurve.cs
- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Plane.cs
- Elements/src/Geometry/TrimmedCurve.cs
- Elements/src/Geometry/Vector3.cs
- Elements/src/Geometry/Vector3Extensions.cs
- Elements/src/Math/Equations.cs
- Elements/src/Spatial/Grid2d.cs
- Elements/src/Units.cs
- Elements/test/ArcTests.cs
- Elements/test/BezierTests.cs
- Elements/test/CircleTests.cs
- Elements/test/CurveTests.cs
- Elements/test/EllipseTests.cs
- Elements/test/IndexedPolyCurveTests.cs
- Elements/test/InfiniteLineTests.cs
- Elements/test/LineTests.cs
- Elements/test/PlaneTests.cs
- Elements/test/VectorTests.cs
BACKGROUND:
- Intent of this PR is to add Intersects function to ICurve, so it can be called for any pair of curves.
DESCRIPTION:
- There are next curve types that used for intersections: InfiniteLine, Circle, Ellipse and Bezier.
- Line. Arc and Elliptic arc are using intersection function of their base curve but with additional domain checks for each intersection point. Each type doesn't have specific Intersects, only PointOnDomain function implemented.
-  Every pair of ICurve is supported, but for simplicity, now every pair of specific curve type is represented. You can't call circle.Intersects(beizer) for example, only bezier.Intersects(circle). Some duplicating function are there, line ellipse.Intersects(circle) and cirlce.Intersects(ellipse) and they just call each other.
- Using …
> Implement Intersects for ICurve and all subtypes

- Elements.Serialization.IFC/src/Serialization/IFC/IFCElementExtensions.cs
BACKGROUND:
- I was trying to export windows as IFC and found that the geometry didn't look the way I expected:
DESCRIPTION:
- The issue was in extrusion creation logic. We were using Z axis as extrusion direction even if the element had extrusion direction Y axis:
TESTING:
- I tried it locally on my local Windows test model. I can give you access to it. But you can simply create model with extrusion by Y axis, create test and add ToIFC method call.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1018)
> Fix: ifc serialization was using ZAxis as extrusion direction

- Elements.Serialization.IFC/src/Serialization/IFC/IFCElementExtensions.cs
- Elements/src/GeometricElement.cs
- Elements/src/Utilities/SolidOperationUtils.cs
BACKGROUND:
I'm planning to re-use code that creates Csg.Solid from SolidOperation
DESCRIPTION:
Solid creation is moved to a separate class
TESTING:
- I tested it on a few functions. I can share them with you. 
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1022)
> Small refactoring before adding multiple representations

- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
Small refactoring before adding serialization of multiple representations to glb
DESCRIPTION:
Added more general method AddMesh that is reused inside AddTriangularMesh and AddPointsOrLines
TESTING:
- I tried change by republishing my old functions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1027)
> GltfExtensions: mesh creation refactoring

- Elements/src/GeometricElement.cs
- Elements/src/Representations/SolidRepresentation.cs
BACKGROUND:
I changed the GeometricElement.Intersection method to support RepresentationInstances. I playing with Stocking Plan Exporter and noticed that sometimes pdf contains wrong geometry:
DESCRIPTION:
- The issue was that I have changed prev. this method to collect intersection points and only after that add them to the graph. And for the case below it doesn't work:
I changed method to add points like it was before
TESTING:
REQUIRED:
COMMENTS:
- Change log contains data that Intersection method was changed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1042)
> Fix: GeometrisElement.Intersection method

- CHANGELOG.md
- Elements/src/Geometry/Arc.cs
- Elements/src/Geometry/BoundedCurve.cs
- Elements/test/EllipticalArcTests.cs
BACKGROUND:
- ToPolyline() function doesn't work for EllipticalArc
DESCRIPTION:
- This PR fixes the ToPolyline() function inside the BoundedCurve class so that inheriting classes don't get errors. Including EllipticalArc
TESTING:
- Call the new test Elements.Geometry.Tests.EllipticalArcTests.ToPolyline() or call the ToPolyline() method on any class that inherits BoundedCurve
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1041)
> Update ToPolyline function in BoundedCurve

- CHANGELOG.md
- Elements/src/CoreModels/ElementRepresentation.cs
- Elements/src/Representations/ContentRepresentation.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
- Elements/src/Serialization/glTF/NodeExtension.cs
- Elements/src/Serialization/glTF/NodeUtilities.cs
BACKGROUND:
ContentElement doesn't work with RepresentationIstances. Explore rewrites Object3D geometry with data from content url. And at this moment it overrides all children nodes
DESCRIPTION:
- ContentRepresentation contains almost all ContentElement properties. The GlbLocation is stored inside glb node as user extension. No Explore changes needed. 
TESTING:
- https://hypar.io/workflows/1b9f4e24-01d4-4ccc-a4f8-460ebeee27b9
- The unicorn function contains Content representation. It's a first content element from the Catalog input
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1044)
> Added ContentRepresentation

- Elements/src/Model.cs
BACKGROUND:
- Content elements didn't show up with latest elements release, problem starting at this PR #1017 where we stopped calling UpdateRepresentations a second time.  This meant content elements didn't have representations, which means they don't have an object in the threeJS scene, which means we can't replace them with the glb mesh.
DESCRIPTION:
- Call update representation on all sub elements that are automatically added that are geometric elements.
TESTING:
- use this alpha with a function that makes content.
FUTURE WORK:
- Some content was mysteriously appearing still in the SpaceTypes function, knowing why this happened might reveal other inconsistencies in when representations exist or don't
REQUIRED:
COMMENTS:
- - - …
> call update representations on child elements as well

- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- I wasn't getting any stuff when making elbows because I had a non-null representation that was empty. this caused errors during the code for getting render data for element.  we previously wouldn't notice these errors because we wouldn't expect to see any geometry, but now with the alternative path of RepresentationInstances we might expect to see geometry in these cases.
DESCRIPTION:
- add a _csg==null check
TESTING:
- no behavior change.
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1055)
> don't process solid if no csg

- CHANGELOG.md
- Elements.Components/src/SpaceConfiguration.cs
BACKGROUND:
- Configurations could not be rotated, so they were not selected unless they clearly fell within the width and length dimensions of the room
DESCRIPTION:
- This PR adds the AllowRotatation property to the ContentConfiguration class. This will allow to understand that the configuration can be rotated if needed
TESTING:
- To fill the room with furniture, use the "Space Type" function. When filling the rooms, the version of the configuration rotated by 90 degrees should be taken into account (depends on the PR: https://github.com/hypar-io/HyparSpace/pull/73)
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Allow rotation of the ContentConfigurations

- CHANGELOG.md
- Elements/src/Geometry/Mesh.cs
- Elements/src/Geometry/Ray.cs
- Elements/test/RayTests.cs
BACKGROUND:
- Mesh/Ray and Topo/Ray intersection would return the wrong point for closed volumes — it was only returning the first intersection, rather than the nearest, so it was impossible to (e.g.) project a ray down onto a topography and get the location of the intersection. 
- The `RayIntersectTopo` test got blown away by [this PR](https://github.com/hypar-io/Elements/pull/212) with what appears to be some temporary code — it switched from testing `Ray.Intersects(Topography)` to testing `Ray.Intersects(Triangle)`.
DESCRIPTION:
- Checks all near triangles, rather than aborting after the first one.
- Fixes the `RayIntersectsTopo` test
REQUIRED:
- - - …
> fix mesh / topo intersection

- Elements.Serialization.IFC/src/IFCElementExtensions.cs
- Elements.Serialization.IFC/src/IFCToHypar/Converters/FromIfcDoorConverter.cs
- Elements.Serialization.IFC/test/IFCTests.cs
- Elements/src/BIM/Door/Door.cs
- Elements/src/BIM/Door/DoorRepresentationStorage.cs
- Elements/test/DoorTest.cs
BACKGROUND:
- Doors needed some properties exposed for functions... This way doors can be adapted depending on context (e.g. wall thickness)
DESCRIPTION:
- Makes properties public so users can define these in their function as needed
TESTING:
- These are being used in the updated `Doors` and `Interior Partitions` functions
FUTURE WORK:
- Possibly more refactoring as we make this cleaner
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1063)
> rename and make properties accessible

- Elements/src/BIM/Door/Door.cs
- Elements/src/CoreModels/ElementRepresentation.cs
- Elements/src/Representations/CurveRepresentation.cs
- Elements/src/Representations/SolidRepresentation.cs
- Elements/src/Serialization/glTF/GltfExtensions.cs
BACKGROUND:
- Snap points are automatically created from representions, which can create too many snap points available for Elements.
DESCRIPTION:
- Adds Set and Get methods to the ElementRepresentation which checks if a developer has specified their own snap points.
TESTING:
- This workflow features a Doors function which is published using snap points at the ends and middle of the door object. Drag it around and see the snapping.
http://localhost:8080/workflows/818a4543-ce03-4688-bf15-d555407abcdb?view=b09eebe9-9857-4fcf-92e4-e4173e928289
FUTURE WORK:
- There may also be Explore changes required to handle null or empty lists of snap points... but it seems to work just fine.
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> Added methods to set and get snap points

- Elements/src/BIM/Door/Door.cs
BACKGROUND:
- Door enums needed descriptioni and attribute to be used correctly in Explore
- Linework representations were broken up so they aren't a single curve
DESCRIPTION:
- Adds attributes to door properties so enums are used correctly
- Door curves are split into multiple representations for cleanliness
TESTING:
- Play around with Doors in this workflow and ensure no buggy behavior
https://hypar.io/workflows/3faca032-c1b2-46b2-a6d3-80632e5e81fb
FUTURE WORK:
- Hopefully I don't touch Doors anymore! Keeping these kinds of objects in Elements is painful. :(
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1067)
> Door property and representation update

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/src/Spatial/AdaptiveGrid/Edge.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
- There are situation were AdaptiveGrid needs to be changed based on the situation in different ways.
- Right now all updates should be done on top of each other or grid should be reconstructed from the start.
DESCRIPTION:
- Added Clone function that performs deep copy of all grid internal data.
TESTING:
- Added AdaptiveGridClone test.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1064)
> Add AdaptiveGrid.Clone

- Elements/src/BIM/Door/Door.cs
BACKGROUND:
- Handle was not located properly
DESCRIPTION:
- Updates the location of the handle
TESTING:
- Handle should be shown in the correct position regardless of door type and size
https://hypar.io/workflows/26e9fcaf-3b3b-436a-8f44-0ec4b1a7b4aa
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1068)
> handle position fix

- CHANGELOG.md
- Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
- Elements/test/AdaptiveGridTests.cs
BACKGROUND:
- When creating grid from a set of circulation objects I found that some edges disappear.
- After investigation I found a bug in partial overlap of two edges: when one end is outside and one is inside.  
DESCRIPTION:
- Register missing intersection points in `AddCutEdge`.  
- It's not an issue if some of them will appear in the list several times since the list is later ordered and checked for duplicates.
TESTING:
- Added AdaptiveGridAddCutWithOverlap to cover problematic case.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1070)
> `AdaptiveGrid.AddEdge` no longer delete edges in case where new edge partially overlaps old edges without intersections.

- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
BACKGROUND:
- De-serializing folders in tests broke recently because we started falling back to elements if something has an "Id" property, which folders do, but they are not Elements
DESCRIPTION:
- Check if there is a discriminator before falling back to Element or GeometricElement.  non-elements can't fallback to these types even if they have an Id or Representation property.
TESTING:
- try to make/run a function that as a folder as an input.  You will get a de serialization error on de serializing the input, then try with this change.
FUTURE WORK:
- NA
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1073)
> handle folders which look like elemetns but aren't

- Elements/src/Model.cs
- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
BACKGROUND:
- Had an issue with deserialization warnings where they were being accessed in different threads
DESCRIPTION:
- Adds the `ThreadStatic` to ensure that this will not be accessed from other threads
TESTING:
- Deserialization should work running in a published function (I tested with `Doors` function)
FUTURE WORK:
- Make sure we are being thread safe!
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1074)
> Make-deserialization-thread-safe

- Elements/src/CoreModels/RepresentationInstance.cs
- Elements/src/GeometricElement.cs
- Elements/src/Geometry/Circle.cs
- Elements/src/Geometry/Plane.cs
- Elements/src/Geometry/Profile.cs
- Elements/src/Geometry/Solids/Extrude.cs
- Elements/src/Geometry/Solids/Lamina.cs
- Elements/src/Geometry/Triangle.cs
- Elements/src/Geometry/Vertex.cs
- Elements/src/Model.cs
BACKGROUND:
- In a number of cases, our NJsonSchema-generated classes reflected an unintentional strange state: that of being `required` but possibly `null`. This is rarely practically useful: in nearly all cases we want a property to either be required or to permit null, but not both.  
DESCRIPTION:
- Adapts all usage of the `Required.AllowNull` attribute to be either `Required.Always`, or not required. Since these values could always be null anyway, the code is generally able to tolerate their "nullness" — the difference is just whether or not we get a serialization failure if a `null` is omitted from the json. For example:
```
{
Perimeter: [...],
Voids: null
}
``` 
is a valid `Profile`, but 
```
{
Perimeter: [...],
}
```
will throw a deserialization error, even though the code can …
> remove all instances of Required.AllowNull

- Elements.Components/src/ContentCatalogRetrieval.cs
BACKGROUND:
- Ancient catalog retrieval code assumed only a single catalog could exist. Setting a second catalog (as the Space Type function does) would fail — we would see we already had a catalog, and just use that, rather than reading the new one.
- This meant that in cases where more than one space type was specified, all but the first one would be missing all properties. 
DESCRIPTION:
- Resets the catalog to null when setting a new path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1079)
> Fix setting a different catalog

- Elements.Components/src/ContentCatalogRetrieval.cs
- Elements.Components/src/SpaceConfiguration.cs
BACKGROUND:
- We noticed that when a space type was updated in the content catalog that old values for the instance parameters on ContentElements would persists across multiple executions.  
DESCRIPTION:
- When a catalog path is set we want to be sure that the `SpaceConfiguration` class will use that new catalog, so we have to clear the catalog that is used for ContentElement retrieval inside `SpaceConfiguration`
TESTING:
- I've tested this with the `function-SpaceType` function and this resolves the stale instance parameter values
FUTURE WORK:
REQUIRED:
~- [ ] All changes are up to date in `CHANGELOG.md`.~
COMMENTS:
- - - …
> reset space configuration cache when setting catalog path

- Elements/src/extension.dib
BACKGROUND:
- Fixes https://github.com/hypar-io/Elements/issues/1083
DESCRIPTION:
- There were a couple minor bugs in the 3d viewer code which resulted in the far plane calculation being wrong, which would cause models not centered on the origin to be clipped / invisible. There were also a couple other little syntax issues.
TESTING:
- I loaded this model into a notebook and returned it in a cell. (Scratch.dib is a good place to test this out against the local version of extension.dib)
[bad-model.json](https://github.com/hypar-io/Elements/files/15142356/bad-model.json)
FUTURE WORK:
- We should find a way to upgrade the version of threejs in our notebook, so we can support setting DEFAULT_UP to `z` instead of `y`, but the recommended CDN approach for three these days requires `importMaps`, …
> fix some bugs in the notebook viewer

- CHANGELOG.md
- Elements/src/Geometry/Line.cs
- Elements/src/Geometry/Vector3.cs
- Elements/test/LineTests.cs
BACKGROUND:
- Some hy-ccups indicated that while we allowed tolerance within our Walls LOD 200 function, we we're not successfully merging these lines which fell out of tolerance for the merge collinear function
DESCRIPTION:
- Adds a method to orthogonally project a line onto another
TESTING:
- Project line A onto line B and observe line A projected orthogonally onto line B.
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1086)
> project line orthogonally onto another

- Elements.MEP/src/Fittings/FittingRepresentationStorage.cs
- Elements.MEP/src/Fittings/Reducer.cs
BACKGROUND:
- Reducers were not being rendered properly do to (presumably) geometry conflicts from 2 sweeps intersecting.
DESCRIPTION:
- Switches from using `this.Representation` to `this.RepresentationInstances` for Reducer representations.
TESTING:
- Load up a workflow with reducers of various sizes and see them no longer missing.
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1089)
> Use representation instances for reducers

- Elements/src/Element.cs
- Elements/src/Model.cs
- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
- Elements/test/ModelTests.cs
🌌 BACKGROUND:
Suggestion functions generate numerous components for each space, many of which contain repeated information. This redundant data can be stored as shared objects to improve efficiency and reduce duplication.
📋 DESCRIPTION:
This PR:
- Introduces `SharedObjects` serialization to the model, stored as a dictionary structure similar to Elements.
- Adds support for skipping SharedObjects marked with the JsonIgnore attribute during serialization.
- Optimizes elements referencing shared objects by:
- Removing redundant properties from elements that are already present in the referenced shared object during serialization.
🧪 TESTING:
- Tested with [classroom](https://github.com/hypar-io/suggestions-classroom/pull/2) and cafe functions to ensure proper functionality.
- Verified that …
> Optimize model serialization by using SharedObjects for reusable data

- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
BACKGROUND:
- We were encountering dll exceptions due to a dependency in the unit test of pyRevit beta 5. We don't need to pull in pyRevit types, so let's exclude them.
DESCRIPTION:
- Excludes pyRevit from App Domain Assemblies used in Json convert.
TESTING:
- Tested by importing any pringle model with Revit 2025 and pyRevit beta 5.
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1091)
> exclude pyRevitLabs from JSON Convert

- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
🌌 BACKGROUND:
When a function retrieves components created by a suggestion function, they contain a shared object ID. However, during deserialization:
1. The shared object is not yet part of the model and is not properly deserialized.
2. The shared object ID gets stored in `AdditionalProperties`.
3. When cloning the element and assigning a new shared object, the ID from `AdditionalProperties` overrides the correct reference, causing the element to lose its new shared object.
📋 DESCRIPTION:
This PR:
- Deletes the `SharedObject` reference from `AdditionalProperties` during deserialization, preventing incorrect overrides.
🧪 TESTING:
- Re-published the Private Office Suggestion function to confirm the fix.
- Verified that the issue shown in [this …
> Fix SharedObject reference loss by removing it from `AdditionalProperties`

- Elements/src/StandardWall.cs
- Elements/test/ModelTests.cs
- Elements/test/models/Elements/zeroThicknessWalls.json
we want to create room separation lines from zero-thickness walls, which are now "legal" as of wallsversion 2 / 3. This will be needed for the new Walls LOD 200 function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1094)
> support zero-thickness wall deserialization

- CHANGELOG.md
- Elements/src/StandardWall.cs
BACKGROUND:
- ElementsToModel for Walls is throwing errors for our new walls structure which allows for zero thickness.  
- When the wall is added to the model we call UpdateRepresentation, which creates a Polygon to make the shape.
- The polygon constructor removed duplicate vertices and runs validation which fails if there are fewer than 3 vertices, and since a 0 thickness wall results in dulicate vertices, this errors.
DESCRIPTION:
- If a StandardWall of a new wall version has zero thickness don't make a representation
TESTING:
- Pringle function with Wall in Test and WallsLOD200 should produce the right number of walls with zero thickness.  These have both been published with this local version of elements for the time being.
- (WallsLOD200 also has the latest `wall-thickness-2` …
> don't make a representation for zero thickness walls (it errors)

- Elements/src/GridLine.cs
- Elements/src/Serialization/JSON/JsonInheritanceConverter.cs
`GridLine` has three properties that can set its geometry: `Curve`, `Geometry`, and `Line`.
In some workflows (e.g., created by a function and later edited in Pringle), a `GridLine` can enter a corrupt state where:
* `Curve` contains the correct value,
* but it is overwritten during deserialization by `Line` or `Geometry` values,
* leading to incorrect behavior or rendering.
This PR prevents unwanted overwriting of the `Curve` during deserialization:
* Introduces a `deserializationIsInProgress` flag:
* Set to `true` inside the `JsonConstructor`.
* Reset to `false` in the `OnDeserialized` callback.
* Modifies the `Line` and `Geometry` setters to **skip assigning to `Curve`** during deserialization, preserving the original `Curve` if it's already set.
* Enabled the `suggest-everywhere` …
> Prevent curve overwrite during GridLine deserialization
