hypar-io/Elements

.travis.yml
src/cli/Commands/Cognito.cs
src/cli/Commands/NewCommand.cs
src/cli/Commands/PublishCommand.cs

The CLI now generates a function that works. The code in the default function that is created still throws an exception, but the function itself packages and deploys correctly.

CLI is now producing a working function.

---

src/cli/Commands/Cognito.cs
src/cli/Commands/PublishCommand.cs

This PR removes the need to create buckets for functions. There are now buckets for the dev and production functions which the CLI writes to.

Use pre-allocated buckets.

---

csharp/src/sdk/Elements/Floor.cs
csharp/src/sdk/Elements/Messages.cs
csharp/src/sdk/Elements/Space.cs
csharp/test/Hypar.SDK.Tests/SpaceTests.cs

Configured Space as a Polyline and a Height.
Added a new Message to notify of Height <= 0.
Added relevant tests, a subset of the Mass tests.

Added initial Space object

---

csharp/src/revit/hypar.revit.csproj

Update the Revit addin to the newest version of the SDK.

Update to newest SDK.

---

src/Elements/Space.cs

in the contructor where a profile is used to created the geometry especially.

Space element should save profile 

---

CHANGELOG.md
src/Elements/Floor.cs
src/Elements/Frame.cs
src/Elements/Geometry/BBox3.cs
src/Elements/Geometry/Interfaces/IExtrude.cs
src/Elements/Geometry/Interfaces/ILamina.cs
src/Elements/Geometry/Interfaces/ISolid.cs
src/Elements/Geometry/Interfaces/ISweepAlongCurve.cs
src/Elements/Geometry/Kernel.cs
src/Elements/Geometry/Mesh.cs
src/Elements/Interfaces/IHasOpenings.cs
src/Elements/Mass.cs
src/Elements/Model.cs
src/Elements/Opening.cs
src/Elements/Panel.cs
src/Elements/Serialization/IFC/ToIfc.cs
src/Elements/Serialization/glTF/GltfExtensions.cs
src/Elements/Space.cs
src/Elements/StandardWall.cs
src/Elements/StructuralFraming.cs
src/Elements/Wall.cs
test/ExtensionTests.cs
test/FloorTests.cs
test/ModelTest.cs
test/PerformanceTests.cs
test/WallTests.cs

This PR fixes #158. In addition it introduces a number of performance improvements to gltf writing by removing redundant loops and writing directly to `byte[]` instead of `List<byte>`.

Fix issue #158.

---

src/Elements/Geometry/Polygon.cs
test/PolygonTests.cs

Absolute value of Polygon area returned after vertex calculation. Polygon Area test updated with reversed vertex list test as well.

Polygon area fix

---

src/Elements/Serialization/glTF/GltfExtensions.cs
test/GltfTests.cs

When model is empty, write an empty gltf.

---

CHANGELOG.md
src/Elements/Floor.cs
src/Elements/Mass.cs
src/Elements/Panel.cs
src/Elements/Space.cs
src/Elements/StructuralFraming.cs
test/StructuralFramingTests.cs

Added Area property to:
- Panel
- Space
Added Volume property to:
- Floor
-Space
Added positive area calculation to:
- Floor
- Mass
Added positive Volume calculation to:
- StructuralFraming

Positive areas and volumes for architectural Elements

---

README.md

went looking for the changelog and thought it would be nice to be able to click on it 😄

update references of CHANGELOG.md to link to file

---

src/Revit/RevitHyparTools/Create.cs
src/Revit/RevitHyparTools/RevitExtensions.cs
src/Revit/RevitHyparTools/RevitHyparTools.csproj

BACKGROUND:
We desire to extract Revit elements to bring them onto Hypar.  We are starting by supporting some construction workflows which need us to extract floor, walls and columns.
DESCRIPTION:
This project contains just the Revit functionality to extract floors.  It's analyses the underlying Revit geometry of the floor elements.
TESTING:
This code cannot be easily tested using this PR alone.  Testing of this library will occur from the Dynamo package released in a subsequent PR
FUTURE WORK:
- This is just floors.   Walls and columns to come.
- Currently uses a small workaround for checking polygon overlap, checking vertices instead of the polygon area itself.  This could be fixed in the future when another PR updates the elements library.
COMMENTS:
None.
--- …

toolkit with functions for creating floors

---

src/Dynamo/src/HyparDynamo/Hypar.cs
src/Dynamo/test/FloorFromFloor.dyn

BACKGROUND:
Need another node in dynamo package to export model to Json
DESCRIPTION:
adds that node
TESTING:
build the dynamo package, see new node
FUTURE WORK:
none
COMMENTS:
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/239)

add a model.toJson node

---

README.md

The link on the README was broken. Please verify that the updated link points to the intended directory in the repo.

Fixed link to tests.

---

src/Elements/Generate/TypeGenerator.cs
test/Elements.Tests/ModelTests.cs
test/Elements.Tests/TypeGeneratorTests.cs

BACKGROUND:
- While working on https://github.com/hypar-io/Hypar/pull/157, I found a number of places where we weren't following proper async patterns.
DESCRIPTION:
- This PR updates a couple of locations in the code to rename functions with proper async indications and to make those functions actually asynchronous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/279)

Proper support for async.

---

src/Elements/Generate/TypeGenerator.cs

BACKGROUND:
- forgot the space
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/339)

whitespace

---

README.md

This PR adds njson schema to the list of 3rd party packages in the Elements README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/341)

Add njson schema to the 3rd party list.

---

CHANGELOG.md

prepping for 0.7.3 official release — updating changelog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/352)

elements changelog

---

README.md

This PR adds a table to the readme which explains the role of the various projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/405)

Update the readme to explain the various projects.

---

.github/workflows/build-and-test-on-pr.yml
Elements.Serialization.IFC/test/IFCTests.cs

Fix #416.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/419)

Fix one test.

---

Elements/src/Geometry/Polyline.cs
Elements/src/Geometry/Solids/Solid.cs
Elements/test/ProfileTests.cs

Unify the transform strategy for two fixes recently applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/430)

Transform fixes

---

Elements.CodeGeneration/src/HyparFilters.cs
Elements.CodeGeneration/src/StringUtilities.cs
Elements.CodeGeneration/src/TypeGenerator.cs
Elements/src/Geometry/Polygon.cs
Elements/src/Serialization/JSON/JsonInheritanceAttribute.cs

BACKGROUND:
- Some classes have been made public without the corresponding doc xml tags being added
DESCRIPTION:
- Add all currently missing  xml summary tags.
TESTING:
- N/A
FUTURE WORK:
- ContentElements are being reviewed in separate PR and will also need documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/415)

add missing xml summaries

---

.github/workflows/publish-on-tag.yml

Attempting to fix the push tags problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/432)

Attempt to fix the push tags problem.

---

Elements/src/Elements.csproj

BACKGROUND:
- csg still doesn't come through when referencing the nuget package
DESCRIPTION:
- add the Pack property set to true.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/431)

pack csg and format

---

.github/workflows/publish-on-tag.yml

Further updates to the publish on release action.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/433)

Publish on release.

---

Elements.CodeGeneration/src/HyparFilters.cs
Elements/src/Serialization/JSON/JsonInheritanceAttribute.cs
Elements/src/Validators/Validator.cs

BACKGROUND:
- managed to merge w/out these changes
DESCRIPTION:
- xml tag additions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/438)

actually fix tags

---

README.md

This PR adds badges for the tag and build, and build and test actions on the front page. It also removes the Travis badge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/439)

Add badges for the actions.

---

Elements/src/ContentElement.cs
Elements/test/ContentTests.cs
Elements/test/GltfTests.cs

BACKGROUND:
- Fix some outstanding issues
DESCRIPTION:
- stop saving glbs to the test folder and add a summary
fixes #441 and #398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/444)

Issue fixes

---

Elements/src/Geometry/Ray.cs
Elements/test/RayTests.cs

fixes #467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/468)

call UpdateRepresentations in Ray.Intersects(GeometricElement)

---

Schemas/ContentCatalog.json
Schemas/ContentElement.json
Schemas/Element.json
Schemas/GeoJSON/Position.json
Schemas/GeometricElement.json
Schemas/Geometry/Arc.json
Schemas/Geometry/BBox3.json
Schemas/Geometry/Color.json
Schemas/Geometry/Curve.json
Schemas/Geometry/Line.json
Schemas/Geometry/Matrix.json
Schemas/Geometry/Mesh.json
Schemas/Geometry/Plane.json
Schemas/Geometry/Polygon.json
Schemas/Geometry/Polyline.json
Schemas/Geometry/Profile.json
Schemas/Geometry/Representation.json
Schemas/Geometry/Solids/Extrude.json
Schemas/Geometry/Solids/Lamina.json
Schemas/Geometry/Solids/SolidOperation.json
Schemas/Geometry/Solids/Sweep.json
Schemas/Geometry/Transform.json
Schemas/Geometry/Triangle.json
Schemas/Geometry/UV.json
Schemas/Geometry/Vector3.json
Schemas/Geometry/Vertex.json
Schemas/Material.json
Schemas/Model.json

This PR corrects all JSON schema ref urls to point to the master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/476)

Udpate refs to correct branch name.

---

.github/pull_request_template.md

This PR updates the pull request template to include a check box for validating that the changelog has been updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/479)

Add the checkbox for Changelog update.

---

.github/pull_request_template.md
.github/release-checklist.md

BACKGROUND:
We've recently implemented CI/CD on Elements, but a number of steps still require manual intervention like building the docs.
DESCRIPTION:
This PR introduces a release checklist to remind those conducting a release of the required steps to release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/495)

Create a release check-list.

---

CHANGELOG.md
Elements/src/Geometry/BBox3.cs
Elements/test/BBox3Tests.cs

BACKGROUND:
- #598 
DESCRIPTION:
- Creates a new constructor for BBox3 that takes an element. This will find the bounding box for any MeshElement, ModelPoints, ModelCurve, ElementInstance, Profile, or GeometricElement. 
TESTING:
- A new test is added which creates all of these element types, ensures no exceptions are thrown, and generates a test model for visual verification: 
REQUIRED:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/601)

Bbox3 from Element

---

.github/workflows/build-and-publish-alpha.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/654)

remove ' to fix action

---

CHANGELOG.md
Elements/src/Geometry/Line.cs
Elements/test/LineTests.cs

BACKGROUND:
- I want to approximately compare lines.
DESCRIPTION:
- Add a method for comparing lines allowing for directional dependence if desired 
- Add tests.
TESTING:
FUTURE WORK:
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/661)

approximate line equals

---

Elements/src/Floor.cs
Elements/src/GeometricElement.cs
Elements/src/Geometry/Polygon.cs
Elements/src/WallByProfile.cs
Elements/test/PolygonTests.cs
Elements/test/WallTests.cs

BACKGROUND:
- Wall by profile needed some adjustments as I continued to work with it 
DESCRIPTION:
- Don't include a Profile property, use the inherited one (the property overloading caused deserializations to be null)
- Add an even more bare constructor, no openings.
- add an AddOpenings method.
- Change UpdateRepresentation fallback logic 
TESTING:
- Mostly this is related to uses in Revit, but tests should continue to pass.
FUTURE WORK:
- Need to update JSON to Model to use latest elements so that openings render correctly.
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/678)

tweaks to wall by profile

---

CHANGELOG.md
Elements/src/WallByProfile.cs

BACKGROUND:
- What led to this work, and what is the broader context of this change?
DESCRIPTION:
- What does this PR specifically accomplish?
TESTING:
FUTURE WORK:
REQUIRED:
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/681)

add null check for openings

---

Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs

Skip tiny domains near start or end of the range. Line.PointAt doesn't like such domains. 
This would lead to degenerated line and exception.
Improve performance of adding region by checking against global bounding box first
BACKGROUND:
This PR solves two situations:
- When working with AdaptiveGrid, it's creation was sometimes failing with exception because of small cells near beginning or end of the domain. In this case  Line.PointAt transformed these values near 0 or 1 into exactly 0 or 1. This led to changing something like [0; 5e-6] into [0; 0] - degenerated line.
- AdaptiveGrid.AddEdge was too slow because it checked each existing line for intersection with new one.
DESCRIPTION:
- Add check for tiny border cells and skip any found.
- Add bounding box check before doing any …

Improvements to AdaptiveGrid

---

Elements/test/GeometricElementTests.cs

I wrote a test just to play with your PR #704 , and I figured it wasn't a bad idea to have a test-as-example for this API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/711)

GraphicsBuffer test

---

CHANGELOG.md
Elements.Benchmarks/CsgBenchmarks.cs

BACKGROUND:
- I committed directly to master by accident
DESCRIPTION:
- Revert two commits
TESTING:
- N/A
FUTURE WORK:
- N/A
REQUIRED:
-N/A [ ] All changes are up to date in `CHANGELOG.md`.
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/729)

Revert mistakes

---

Elements/src/extension.dib

sets the renderer for the notebook preview to have a transparent background
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/746)

transparent background for viewer

---

CHANGELOG.md

BACKGROUND:
- Need to kick off 0.9.9 alpha stream
DESCRIPTION:
- Stub 0.9.9 changelog
TESTING:
- N/A
FUTURE WORK:
- N/A
REQUIRED:
COMMENTS:
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/750)

docs: Begin changelog for 0.9.9

---

Elements/src/Spatial/AdaptiveGrid/AdaptiveGrid.cs
Elements/test/AdaptiveGridTests.cs
README.md

BACKGROUND:
- Didn't quite have the AdaptiveGrid documentation example code and glb wired up correctly
DESCRIPTION:
- change glb name and add `example` tags inside test code.
- update readme with some instructions.
TESTING:
- run `build_docs.sh` to see the glb now loading correctly.
FUTURE WORK:
REQUIRED:
~- [ ] All changes are up to date in `CHANGELOG.md`.~
COMMENTS:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/789)

Adaptive grid examples

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/796)

Update the README for 1.0

---

.gitignore
CHANGELOG.md
Elements/src/FileDestination.cs

BACKGROUND:
- We want to enable any old function on Hypar to export files, and so we are creating a new type, meant to be used with inputs, that represents a destination for a file to be saved.
DESCRIPTION:
- Create FileDestination class that has an internal "Stream` which can be set by the user in a couple of ways.
TESTING:
- The function called "Test Exporter" uses this version of elements.  you need to use this sandbox.  https://file-destinations.sandbox.hypar.io/ 
FUTURE WORK:
- Probably need more utility methods to ensure safe function operations.  
- `Extension` exists for testing but is not consistently filled in correctly, need to figure out why.
REQUIRED:
COMMENTS:
--- …

File destination element

---

.github/workflows/build-docs.yml

BACKGROUND:
- docs were updating pointing to outdated s3 buckets.
DESCRIPTION:
- push changes to our docs folder in this repo instead of to the s3 buckets.
TESTING:
- we'll run a release if we think this merge is ok.
FUTURE WORK:
- should delete outdated secrets
REQUIRED:
- ~[ ] All changes are up to date in `CHANGELOG.md`.~
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/853)

use add and commit for docs

---

.github/workflows/build-docs.yml

BACKGROUND:
- yaml syntax is hard
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/859)

fix syntax

---

CHANGELOG.md
Elements/src/Geometry/Polygons.cs
Elements/test/PolygonTests.cs

BACKGROUND:
I wanted a U-shaped polygon as part of our static collection of polygons.
DESCRIPTION:
This PR adds `Polgons.U`.
TESTING:
No new tests have been added. It's just a U.
FUTURE WORK:
We should support E, H, and O as other building-shape letter types.
REQUIRED:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/elements/888)

Make a new U polygon type.

---

.github/workflows/build-and-publish-alpha.yml
.github/workflows/build-and-test-on-pr.yml
.github/workflows/build-docs.yml
.github/workflows/publish-on-tag.yml
Directory.Build.props
Elements.Benchmarks/Elements.Benchmarks.csproj
Elements.CodeGeneration/test/Elements.CodeGeneration.Tests.csproj
Elements.Components/test/Elements.Components.Tests.csproj
Elements.Serialization.DXF/src/Elements.Serialization.DXF.csproj
Elements.Serialization.DXF/tests/Elements.Serialization.DXF.Tests.csproj
Elements.Serialization.IFC/test/Elements.Serialization.IFC.Tests.csproj
Elements.Serialization.SVG/src/Elements.Serialization.SVG.csproj
Elements.Serialization.SVG/test/Elements.Serialization.SVG.Tests.csproj
Elements/test/ContentTests.cs
Elements/test/Elements.Tests.csproj

BACKGROUND:
- There is a vulnerability in old versions of System.Text.Encodings.Web, referred to by .netcoreapp. 
DESCRIPTION:
- Updates the package to .net6.0
FUTURE WORK:
- Update API services utilizing this library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/953)

update package versions for elements.serialization.dxf

---

Elements.MEP/Examples-Create Tree.dib
Elements.MEP/Examples-Routing Tree.dib

BACKGROUND:
- gotta references alphas for Element.Hypar.MEP nugets to work.
DESCRIPTION:
- Update refs
TESTING:
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1033)

fix dib nuget imports

---

Elements.Components/src/SpaceConfiguration.cs

BACKGROUND:
- I approved a spelling mistake in #1060 
DESCRIPTION:
- fix the mistake
TESTING:
- N/A
FUTURE WORK:
REQUIRED:
~- [] All changes are up to date in `CHANGELOG.md`.~
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1061)

spelling fix

---

CHANGELOG.md
Elements.Components/src/SpaceConfiguration.cs

BACKGROUND:
- Add additional properties to ContentConfiguration for future easier compatability.
DESCRIPTION:
- Add the additional properties dictionary mirroring how we treat elements.
TESTING:
- Tests still pass, good enough for now.
FUTURE WORK:
REQUIRED:
COMMENTS:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hypar-io/Elements/1072)

additional props on contentConfigurations
